### ISSUE TITLE
adopt std::legendre

### ISSUE THREAD

**Issue by grahamlopez** [project-asgard/asgard#125]
We could reduce our maintenance footprint a little bit by outsourcing the legendre-related functionality to the standard library. David and I have talked briefly about this, and there doesn't seem to be any major issues with this.

However, some things to consider:
- both the matlab and c++ would want to make this adoption to builtin/provided functions
- there are matters of normalization to be taken into account in both the matlab and c++

**Comment by grahamlopez** [comment]
A small note: this is only currently provided in libstdc++, but the code has been submitted to libc++, so should be there in the future.
https://reviews.llvm.org/D60234

**Comment by mkstoyanov** [comment]
Stale issue, open a new one, if still relevant.
