### ISSUE TITLE
Notes on main

### ISSUE THREAD

**Issue by dlg0** [project-asgard/asgard#126]
Some notes on `main.cpp`
- [x] it does not work :slightly_smiling_face: i.e., while the time_advance tests pass, i get all zeros out of running the actual code for the `fokkerplanck_1d_4p2` PDE (see my `fokkerplanck1_4p1a` branch).
- [x] system() should be renamed to something more descriptive.
- [x] system.batch_output is the solution vector. Perhaps we could name it as such? (i.e., avoiding lines like `diff = system.batch_output - analytic_solution_t`
- [x] what is `x_orig` and where is it used?

**Comment by bmcdanie** [comment]
we no longer have these items in main @dlg0. I may use this issue as an opportunity to re-evaluate main for readability, though.

**Comment by bmcdanie** [comment]
closed with #229 - but need to periodically reevaluate main for conciseness and clarity.
