### ISSUE TITLE
compiler warning audit

### ISSUE THREAD

**Issue by grahamlopez** [project-asgard/asgard#131]
It would be worthwhile for someone to understand the yet unused warnings that are available, and to reason out which ones we want and which we don't.

**Comment by bmcdanie** [comment]
clang flags overview: https://clang.llvm.org/docs/DiagnosticsReference.html

warning against routine use of `-Weverything ` flag in clang: https://quuxplusone.github.io/blog/2018/12/06/dont-use-weverything/

gcc flags overview: https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html

It looks (to me) like our best option is `-Wall`, `-Wextra` and `-Wpedantic` for warnings, and then of course either debug/optimization flags for debug/release builds @grahamlopez.

**Comment by bmcdanie** [comment]
additionally could use `-fno-exceptions`: https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_exceptions.html
