### ISSUE TITLE
Remove duplication of code from _tests.cpp

### ISSUE THREAD

**Issue by dlg0** [project-asgard/asgard#144]
In `time_advance_tests.cpp` we use a lot of duplicate setup code just to test each of the PDEs. This needs to be cleaned up such that we use the setup code from the main program itself, rather than this duplicate - but possibly different from the real code - version. 

It is also a pain to maintain if anything in the setup code changes, since every PDE test code has to be updated.

**Comment by grahamlopez** [comment]
Now that you have pointed it out, I am starting to see this in other places besides `time_advance`.

**Comment by grahamlopez** [comment]
just some more discussion:
something to consider here is that the macro system used by Catch2 is designed to maximally isolate each test case but allow reuse. see https://github.com/catchorg/Catch2/blob/master/docs/tutorial.md#test-cases-and-sections specifically
> For each SECTION the TEST_CASE is executed from the start

and 

> Sections can be nested to an arbitrary depth (limited only by your stack size). Each leaf section (i.e. a section that contains no nested sections) will be executed exactly once, on a separate path of execution from any other leaf section (so no leaf section can interfere with another).

**Comment by bmcdanie** [comment]
closed by #193
