### ISSUE TITLE
Build instructions for Cori GPU fail

### ISSUE THREAD

**Issue by bcfriesen** [project-asgard/asgard#145]
Following the [build instructions for Cori GPU](https://github.com/bmcdanie/ASGarD/tree/feature/gpus#cori-gpu-node-nersc), I encounter an error while compiling OpenBLAS:

```console
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot find -lgfortran
collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:145: ../libopenblas_skylakexp-r0.3.4.so] Error 1
make[3]: *** [Makefile:101: shared] Error 2
make[2]: *** [CMakeFiles/openblas-ext.dir/build.make:115: contrib/blas/openblas/src/openblas-ext-stamp/openblas-ext-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:548: CMakeFiles/openblas-ext.dir/all] Error 2
make: *** [Makefile:95: all] Error 2
```

Here are my modules:

```console
esslurm                                              2019/07/30  7:37:02
cuda/10.1.168                                        2019/08/15  0:20:04
gcc/8.2.0                                            2018/11/01 10:37:51
cmake/3.14.4                                         2019/07/25 23:27:47
```

**Comment by dlg0** [comment]
I doubt we should be building our own openblas here. Perhaps some cmake tweaks are required @grahamlopez ?

**Comment by bcfriesen** [comment]
FYI, it looks like Cori GPU already has `libblas` and `liblapack` installed via zypper:

```console
friesen@cgpu01:~> find /usr -name '*libblas*' 2>/dev/null
/usr/lib64/libblas.so.3
friesen@cgpu01:~> find /usr -name '*liblapack*' 2>/dev/null
/usr/lib64/liblapack.so.3
friesen@cgpu01:~> nm -D /usr/lib64/liblapack.so.3|grep dgesv
000000000202a6c0 T LAPACKE_dgesv
000000000202a790 T LAPACKE_dgesv_work
000000000202aa80 T LAPACKE_dgesvd
000000000202aca0 T LAPACKE_dgesvd_work
000000000202b3e0 T LAPACKE_dgesvdx
000000000202b6d0 T LAPACKE_dgesvdx_work
000000000202be30 T LAPACKE_dgesvj
000000000202c060 T LAPACKE_dgesvj_work
000000000202c530 T LAPACKE_dgesvx
000000000202c860 T LAPACKE_dgesvx_work
000000000014f580 T dgesv_
0000000001aebf10 T dgesvd_
0000000001af54f0 T dgesvdx_
0000000001bce050 T dgesvj_
0000000001af75a0 T dgesvx_
friesen@cgpu01:~> nm -D /usr/lib64/libblas.so.3 |grep ddot
0000000000145310 T cblas_ddot
0000000000144380 T ddot_
0000000000f4fc00 T ddot_k_ATOM
0000000000c72800 T ddot_k_BARCELONA
0000000000dfc600 T ddot_k_BOBCAT
0000000001282600 T ddot_k_BULLDOZER
000000000055c400 T ddot_k_CORE2
000000000076d400 T ddot_k_DUNNINGTON
00000000015e1180 T ddot_k_EXCAVATOR
000000000170bcc0 T ddot_k_HASWELL
0000000001034000 T ddot_k_NANO
0000000000869130 T ddot_k_NEHALEM
0000000000996c00 T ddot_k_OPTERON
0000000000b03600 T ddot_k_OPTERON_SSE3
0000000000666800 T ddot_k_PENRYN
00000000013a2060 T ddot_k_PILEDRIVER
00000000003dea00 T ddot_k_PRESCOTT
0000000001146340 T ddot_k_SANDYBRIDGE
00000000014c1f80 T ddot_k_STEAMROLLER
000000000187e6c0 T ddot_k_ZEN
friesen@cgpu01:~>
```

**Comment by bmcdanie** [comment]
Hi Brian - I am looking into that now for you.

Perhaps my instructions assumed that the default loaded modulefiles were the same for everyone. My build found the MKL BLAS/LAPACK and linked to those, but I see that the `intel` module is loaded by default. Were the above listed modules the only ones you had installed?

It also seems that if I force openblas build with `-DASGARD_BUILD_OPENBLAS=1`, I also get a compile error related to a missing AVX instruction @grahamlopez when `CC = gcc` . Not immediately obvious why - openblas appears to detect the correct architecture. icc does not fail in this case. also note the modulefiles for compilers on this system do not export `CC` and `GCC` - I need to add that to the instructions.

Please post the entire `cmake --verbose` command line and output for any future build issues to help us track it down for you!

**Comment by bcfriesen** [comment]
Hi @bmcdanie,

> Perhaps my instructions assumed that the default loaded modulefiles were the same for everyone. My build found the MKL BLAS/LAPACK and linked to those, but I see that the intel module is loaded by default. Were the above listed modules the only ones you had installed?

Ah, that makes a difference. I notice in your build instructions for Cori GPU you say:

```console
ssh cori.nersc.gov
module load esslurm
```

but in fact NERSC [recommends](https://docs-dev.nersc.gov/cgpu/software/) that users `module purge` before doing `module load esslurm`, because nearly all of the modules which are loaded by default when one logs into a Cori login node are non-functional on Cori GPU. Since you do not purge your modules before getting a GPU node, you still have the `intel` module loaded, which seems to be how CMake finds MKL.

I verified that loading the `intel` module fixes the link error, and also avoids building OpenBLAS altogether. So this set of modules fails:

```console
esslurm                                              2019/07/30  7:37:02
modules/3.2.11.1                                     2018/10/25 20:23:19
gcc/7.3.0                                            2018/11/01 10:31:32
cuda/10.1.168                                        2019/08/15  0:20:04
cmake/3.14.4                                         2019/07/25 23:27:47
```

but this set of modules succeeds:

```console
esslurm                                              2019/07/30  7:37:02
modules/3.2.11.1                                     2018/10/25 20:23:19
gcc/7.3.0                                            2018/11/01 10:31:32
cuda/10.1.168                                        2019/08/15  0:20:04
cmake/3.14.4                                         2019/07/25 23:27:47
intel/19.0.3.199                                     2019/06/27 18:18:57
```

and the code runs successfully.

**Comment by bcfriesen** [comment]
It might be worth modifying the CMake recipe to look in `/usr/lib64` if it can't find MKL. Or just add `module load intel` to the build instructions.

**Comment by bcfriesen** [comment]
> and the code runs successfully.

Oops, spoke too soon. Is the below error (warning?) message significant?

```console
friesen@cgpu01:~/NESAP/ASGarD/asgard.git/build> srun -n 1 -c 2 ./asgard continuity_6 -l 3 -d 4
Branch: HEAD
Commit Summary: 4c16add7aa6dc83678317441ae3732d4fec59b5f
  Date: Mon Aug 19 16:29:12 2019 -0400
      fix missing line
This executable was built on Wednesday, August 21 2019 at  8:46 am
Error in command line parsing: Unrecognised token: continuity_6
generating: pde...
ASGarD problem configuration:
  selected PDE: continuity_2
  level: 2
  degree: 2
  N steps: 10
  write freq: 0
  vis. freq: 0
  implicit: 0
  full grid: 0
  CFL number: 0.1
  Poisson solve: 0
```

**Comment by bmcdanie** [comment]
yes - I am missing a flag (`-p`) before continuity_6.  I will roll this in when I fix the other build instructions.

**Comment by bmcdanie** [comment]
fixed, and tested. see https://github.com/project-asgard/asgard/wiki/platforms#cori-gpu-node-nersc.
