### ISSUE TITLE
Workspace naming

### ISSUE THREAD

**Issue by bmcdanie** [project-asgard/asgard#148]
`host_space` and `rank_space` have been marked as confusing for multiple people. bikeshed this.

**Comment by bmcdanie** [comment]
related to #126

**Comment by bmcdanie** [comment]
@grahamlopez did we make a decision here? `rank_space` and `node_space`?

**Comment by stonecoldhughes** [comment]
`host_space` is the only one that needs renaming, correct? Possibilities:
`cpu_space`?
`default_space`?
`global_space`?

**Comment by grahamlopez** [comment]
We have been discussing this and discovered that no matter what kind of naming scheme we come up with, there is information that is being left out. So asking ourselves, "what is the important info to convey about the differences in these memory spaces?" we came up with

1. It is potentially expensive to transfer memory into/out of it
2. It is potentially restricted in size

Given these criteria, `host_space` and `device_space` most clearly communicate these two points. It is also consistent with the `resource_type` from the `tensors` component, which nobody has complained about or seems to be confused about. It _doesn't_ convey that `device_space` is also used when there is no device present, but again this is also the case for the device-type tensors which has not caused problems. With the above observation that we haven't found any naming that includes all information with no ambiguities, having names that give the important information and depending on folklore knowledge for the details is the best we have come up with.

I would love to be proven wrong. In the absence of other suggestions, we will submit a PR to change `rank_space` to `device_space` as part of issuethon - hopefully within the week. (Notice: @dlg0 and @elwasif)

**Comment by dlg0** [comment]
it should be blue!

`device` to me can mean whatever resource backend we are using to do the heavy lifting. And just so I'm clear, in the case where `device` is CPU only, do we actually still copy into `device_space` or just use the `host_space` memory? (it sounds like we do) In that case, I think I'm OK with it. So your proposal makes sense to me.

**Comment by bmcdanie** [comment]
there are some limited places where we copy `host` tensors into `device` ones.

this occurs because we want the full tensors api to build some matrices/vectors (using `host`) and then restrict the API once we may be using GPUs (using `device` tensors).

@grahamlopez and I discussed the piece we need to add to remove these redundant allocations - a `host` to `device` tensor function that performs in a move-like way when both `host` and `device` are in CPU RAM and performs a PCI transfer when `device` is actually on a device.

I can start an issue for that.

**Comment by grahamlopez** [comment]
@dlg0,

@bmcdanie gave the long answer, but the short answer to your question is 'yes'; your intuition is correct. The device flavors of both the tensors and the "workspaces" get used even when there is no gpu and the compute is happening on the cpu only.

The optimization that @bmcdanie refers to of avoiding the extra copy for the special case of "device == cpu" is a somewhat separate issue; it doesn't change any semantics and doesn't really have any bearing on the discussion of this thread's topic.

**Comment by efdazedo** [comment]
If the amount of duplication (when device == cpu host) is not significant, then IMHO it is not important (or lower priority)  in terms of data movement or memory usage. Maybe collect some profiling timing data or memory use data  from actual use cases to see how important is this.

**Comment by grahamlopez** [comment]
@efdazedo I completely agree; it is low priority and I would expect it to be more of a simplification benefit than performance.
