### ISSUE TITLE
enable matrix inversion/determinant for integral matrices

### ISSUE THREAD

**Issue by grahamlopez** [project-asgard/asgard#15]
ASGarD
    asgardasgard
    Issues
    #15

Open
Opened 5 months ago by Graham Lopez
Close issue
New issue
enable matrix inversion/determinant for integral matrices

This is probably lower priority; I'm not sure that we'll actually need this. It would be nice for completeness.
Edited 5 months ago by Graham Lopez
Related issues
0

Related merge requests
1

    Feature/templated tensors
    asgard/asgard !13

    Graham Lopez @bgl changed the description 5 months ago
    Graham Lopez @bgl mentioned in merge request !13 (merged) 5 months ago
    Graham Lopez @bgl added someday label 5 months ago

**Comment by bmcdanie** [comment]
we have no current use case for this, closing for now.
