### ISSUE TITLE
clara no longer maintained

### ISSUE THREAD

**Issue by bmcdanie** [project-asgard/asgard#151]
noticed when using clara (https://github.com/catchorg/Clara) for another project that the readme has been updated to indicate it's no longer maintained.

the tool is doing what we want it to do and is isolated in the `program_options` component, but we may want to move to something maintained at some point.

**Comment by grahamlopez** [comment]
Phil Nash said to maybe look into Argh: https://github.com/adishavit/argh

**Comment by mkstoyanov** [comment]
Stale issue, will look into this if it becomes a problem.
