### ISSUE TITLE
Changing CFL causes tests to fail

### ISSUE THREAD

**Issue by stonecoldhughes** [project-asgard/asgard#152]
The default Courant–Friedrichs–Lewy condition (cfl) has a value of 0.1 set in program_options.hpp. Running problems from the command line with this default value causes enormous RMSE error. Reducing the cfl to 0.01 causes better RMSE for command-line runs but causes several tests in which the cfl is not explictly set to fail.

**Comment by bmcdanie** [comment]
@dlg0  do we want to change the default CFL?

**Comment by dlg0** [comment]
Yes. 0.01 is better and is what is used in the matlab.
