### ISSUE TITLE
Constructing a PDE with num_dims_=2, but only defining 1 dimension still compiles

### ISSUE THREAD

**Issue by dlg0** [project-asgard/asgard#158]
```
static int constexpr num_dims_           = 2;
```
and
```
inline static std::vector<dimension<P>> const dimensions_ = {dim_p};
```
should this still compile? (because it does)

**Comment by bmcdanie** [comment]
the assert is at runtime, so it will combine but abort at runtime: https://github.com/project-asgard/asgard/blob/241469c4e80dca0809ab74975c3ee2937519f849/src/pde/pde_base.hpp#L359.

we may need to consider static asserts for some of these, but I believe that would move the asserts into the (potentially) user-provided pde.

**Comment by dlg0** [comment]
OK. Thanks.
