### ISSUE TITLE
Rename exact solution functions in PDE

### ISSUE THREAD

**Issue by dlg0** [project-asgard/asgard#159]
Rename `exact_vector_funcs_` to something like `exact_solution_funcs_MD_` (the type tells me it's a vector of vectors - don't need it in the name - tell me what it is, i.e., the exact solution functions for each dimension (i.e, a Multi-Dimensional quantity - which I propose we tag with `_MD` - and also `_1D` for one dimensional quantities where appropriate. In the matlab I was using `1D` and `nD`, but if the C++ standard thinks `MD` is good for multidimensional, who am I to argue. 

Similarly for `exact_scalar_func_` to something like `exact_solution_func_time_`

**Comment by grahamlopez** [comment]
here the "vector" in the name is referring to the fact that they are vector functions, as opposed to scalar functions. Has nothing to do with the data structure.

*md is okay, but no need to YELL about it

**Comment by dlg0** [comment]
So acronyms in lower case ... ?

**Comment by dlg0** [comment]
Using vector (in the this-has-several-components physics sense) so close to a vector of a vector in the C++ sense I think is confusing.

**Comment by mkstoyanov** [comment]
Stale issue, open a new one, if still relevant.
