### ISSUE TITLE
What is the point of num_terms_?

### ISSUE THREAD

**Issue by dlg0** [project-asgard/asgard#162]
In a PDE there is a private member

```
  static int constexpr num_terms_          = 1;
```
which if that number does not equal then length of the `term_set`

```
  inline static term_set<P> const terms_ = {termC1, termC2};
```
we get a runtime error. 

Is this actually catching anything useful? i.e., what would be the problem with just inferring `num_terms_` from `terms_.size()`?

**Comment by grahamlopez** [comment]
@bmcdanie can confirm, but IIRC this was to check that a pde was implemented self-consistently, esp. in the case of a user-supplied pde.

**Comment by bmcdanie** [comment]
that's correct.

**Comment by stonecoldhughes** [comment]
is everyone happy with this? Can I close the issue?

**Comment by dlg0** [comment]
Certainly we want to check for consistency within the PDE. I'm just not sure I understand why this could not be achieved by setting `num_terms_` after the PDE is defined by looking at the `terms_.size()` and then checking for consistency. If we are already doing runtime checking then doing it this way would mean I don't have to go and set `num_terms_` effectively in two places, i.e., by changing `terms_ = {termC1, termC2}` to `terms_ = {termC1}` and then additionally changing  `num_terms_ = 2` to `num_terms_ = 1`. It's that extra step I don't like. Now if we were doing compile time checking, I could live with it. Did that clarify my issue with this?

**Comment by mkstoyanov** [comment]
Stale issue, open a new one, if still relevant.
