### ISSUE TITLE
modify realspace transform to work with partial solution vector

### ISSUE THREAD

**Issue by bmcdanie** [project-asgard/asgard#182]
wavelet to realspace transform iterates through every element in the element table, transforming the solution values for each to real space.

the MPI feature distributes the solution vector across ranks - none have the entire solution vector. modify the wavelet to realspace transform to only iterate over the elements assigned to a given rank (i.e. in its subgrid) and create a partial realspace solution.

we will need to determine how to reassemble these, or dump them to disk and handle it with post-processing (spark?).

**Comment by stonecoldhughes** [comment]
assembling them should be as simple as adding them all together. Probably should be an option as to whether MPI should do that or just dump partial results and leave it as a post processing task

**Comment by stonecoldhughes** [comment]
how about a post-processing routine in the distribution component that gathers and reduces the partial solutions with MPI? In the case that a node's partial solution is too long, the routine will receive it in sections. This does not require SPARK or any other dependencies.

**Comment by bmcdanie** [comment]
this should be addressed by the scalable realspace transform PR so I'm excluding from the issuethon. Refer to this issue in that PR @stonecoldhughes .

**Comment by mkstoyanov** [comment]
Stale issue, open a new one, if still relevant.
