### ISSUE TITLE
Intel v19.0.3.199 fails to compile `transformations_tests.cpp`

### ISSUE THREAD

**Issue by bcfriesen** [project-asgard/asgard#225]
See attached [build.txt](https://github.com/project-asgard/asgard/files/4042656/build.txt).

**Comment by bmcdanie** [comment]
it looks like intel compiler support is not complete for c++17:
https://software.intel.com/en-us/articles/c17-features-supported-by-intel-c-compiler

strangely, the warnings appear on extern template declarations, a C++11 feature. need to check to see if the lines marked non-standard in warnings violate the spec.

**Comment by bmcdanie** [comment]
14.7.2, para 13 discusses default arguments and `extern template`s but it's unclear if default arguments are expressly forbidden in `extern template`s. Since they're redundant, we should probably take them out anyway.

**Comment by bmcdanie** [comment]
to be clear, there are also errors that appear on C++17 features, I was just wondering why the `extern template` warnings appeared as that is an 11 feature.

**Comment by mkstoyanov** [comment]
Stale issue, open a new one, if still relevant.
