### ISSUE TITLE
Right way to add Matlab files for processing output to the repository

### ISSUE THREAD

**Issue by tyounkin** [project-asgard/asgard#238]
I've made an initial commit of some Matlab files in a processing folder. Any thoughts about grouping these with the corresponding PDEs or elsewhere? @dlg0 @grahamlopez @adam-mcdaniel

**Comment by bmcdanie** [comment]
if these are strictly post-processing scripts, I'd suggest creating a new repository within this project-asgard project, and placing them there, with a readme to indicate how they're used @tyounkin .

**Comment by dlg0** [comment]
Did this repo get created? If so, can we close this?

**Comment by bmcdanie** [comment]
@dlg0 not yet as far as I know, files sitting in this other branch but not posted to new repo.

**Comment by dlg0** [comment]
@tyounkin can we get this moved to another repo under project-asgard?

**Comment by mkstoyanov** [comment]
Stale issue, open a new one, if still relevant.
