### ISSUE TITLE
Add missing runaway electron PDE and ensure matches to RE paper

### ISSUE THREAD

**Issue by tyounkin** [project-asgard/asgard#240]
For the run-away electron manuscript still being worked on, ASGarD PDEs should match. There was one PDE missing, and exact run-parameters should be documented.

**Comment by bmcdanie** [comment]
@dlg0 which pde is this? I can add this pde if it is not already present

**Comment by dlg0** [comment]
i think this is `fokkerplanck2_complete`, but I thought that was already in there?

**Comment by bmcdanie** [comment]
it is indeed implemented in the C++...so perhaps this is a dead issue?

**Comment by dlg0** [comment]
Y

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bmcdanie** [comment]
closing as feature is already implemented
