### ISSUE TITLE
Time-independent A matrix

### ISSUE THREAD

**Issue by lwonnell** [project-asgard/asgard#277]
**Is your feature request related to a problem? Please describe.**
In the Matlab code, it is possible to have a time-independent A matrix. This tends to speed up implicit runs. There does not seem to be an option for the C++

**Describe the solution you'd like**
A program option allowing for a time-independent A matrix

**Comment by bmcdanie** [comment]
hey @lwonnell . this is the default in the C++ - we have not implemented time-dependent coefficients yet, so we are always building the `A` matrix just once.
