### ISSUE TITLE
libkron.so not found on cori's GPU cluster

### ISSUE THREAD

**Issue by PierreCarrier** [project-asgard/asgard#303]
I repeated the Wiki steps for the NERSC Cori's cluster machine, but get the error that libkron.so is not found. The ldd command gives:
 
pcarrier@cori06:/global/cscratch1/sd/pcarrier/ASGARD/src/asgard/build> ldd asga
        linux-vdso.so.1 (0x00002aaaaaad3000)
        libkronmult_cuda.so => /global/cscratch1/sd/pcarrier/ASGARD/src/asgard/
        libkron.so => not found

It seems that cmake  doesn't download the  "kron" library.

**Comment by bmcdanie** [comment]
please pull the latest code and confirm this is fixed at your convenience @PierreCarrier .

**Comment by PierreCarrier** [comment]
Yes that works. Thanks!

**Comment by bmcdanie** [comment]
great!
