### ISSUE TITLE
clean up options/pde relationship - make options const

### ISSUE THREAD

**Issue by bmcdanie** [project-asgard/asgard#304]
we are drawing some options - level, degree, and dt - from one of two sources. users can provide these on the command line. if they don't, defaults are loaded from the pde. 

right now, we are parsing CL input, and creating an options object with a flag for "NO USER VALUE". this is passed to the pde object. if NO USER VALUE is set for level, degree, or dt, defaults are loaded from the pde. next, the options object is updated with the final values from the pde.

this is unnecessarily complex and means the options object in main is not const.

clean up the relationship between the clara parser, options, and PDE so that the PDE and options objects are initialized correctly and synchronized after construction.

**Comment by dlg0** [comment]
I think that the general statement that things in `options` come from the command line and things in `pde` come from the PDE spec could also be true, such that there is no relationship between `pde` and `options`.

**Comment by bmcdanie** [comment]
yes - we could split these things up. separating the parsing from the program options object would allow dt, level, and degree to exist solely in PDE and not in program options at all.

**Comment by dlg0** [comment]
I'd think those things should exist in options, not PDE.

**Comment by bmcdanie** [comment]
well, that is possible too - I only said PDE because that's where the defaults are being drawn from.

**Comment by dlg0** [comment]
I've been working in this direction in the matlab, see ...

https://github.com/project-asgard/DG-SparseGrid/blob/reference/OPTS.m
