### ISSUE TITLE
leverage sparsity in operator matrices

### ISSUE THREAD

**Issue by bmcdanie** [project-asgard/asgard#305]
while implementing max level (build once) operator matrices to enable the adaptivity, I noticed that operator matrix sparsity increases with level. we could add a check for each element that tests whether any of the element's small kronmult matrices are all zeros, and remove those elements from the grid. this would allow us to compute the same answer with fewer elements. does this sound reasonable @dlg0 @efdazedo @MollyRaver ?

**Comment by bmcdanie** [comment]
if we did this, we could store only the dense regions of these matrices and save considerable on-device storage, as well.

**Comment by bmcdanie** [comment]
it's also possible that this is true for some terms, and not for others. in that case, we'd leave the element in the grid, but not compute on it for some terms.

**Comment by bmcdanie** [comment]
from Ed:

There may be true zeros in sparsity pattern based on whether 2 intervals at different levels has overlap.

There may be apparent zeros when those matrix entries are very small and dropped on purpose.  

For true zeros in sparsity pattern based on overlap, I think we can check for overlap just based on the level and interval number and without checking for numerical entries in the matrix.

For the apparent zeros (small entries), these may need to examine the numerical entries.

My hunch is I suspect it is not very often that we encounter such zero matrices (already with interval overlap).

It may be interesting to add this code and print how the batch size changes to see how effective is this short-cut.

**Comment by bmcdanie** [comment]
@dlg0 and Ed pointed out that this is related to the connectivity. 

Connect 1D (lev 10):
![image](https://user-images.githubusercontent.com/7290188/84913283-5e28e280-b088-11ea-917b-a3094edcb171.png)

Portion of operator matrix (lev 7):
![image](https://user-images.githubusercontent.com/7290188/84913447-916b7180-b088-11ea-8dbc-9eeb794d3b1d.png)

So, the 1d connectivity appears to describe the dense regions. Maybe the nd connectivity describes which elements address dense regions in all operator matrices? Will need to check.

**Comment by dlg0** [comment]
I'd think that the 1D connectivity describes the dense regions in the 1D operator mats, and then the nD version describes the nD operators mats after they are tensor product-ed together?

I was under the impression that when we go to nD though, the sparsity goes down significantly.

**Comment by bmcdanie** [comment]
it seems to me that if an element is not connected in any one dimension, its kronmult result will be zero regardless of whether it addresses dense regions in other dimensions or not?

I will run some quick experiments to determine what the 1D and nD connectivities look like as dimension and level vary, at some point.

**Comment by efdazedo** [comment]
Hi Tyler,

Yes, I agree that   in  computing     Y = kron(A1, ..., An) * X,   if any of A1, or A2 ... or An is a zero matrix, then the kron product will be zero.

Ed

**Comment by mkstoyanov** [comment]
Stale issue, open a new one, if still relevant.
