### ISSUE TITLE
Hackathon run details

### ISSUE THREAD

**Issue by dlg0** [project-asgard/asgard#308]
@bmcdanie Let's add to this some reasonable command-line strings for appropriate problem sizes, i.e., 

Small 2D problem
DoF = , MatSize = ??? [GB]
Notes - this is a tiny case, and can be done serially on a laptop.
```
./asgard -p continuity2 -l 5 -d 4 -n 100
```
Large 2D problem
```
./asgard -p continuity2 -l 10 -d 8
```
Small 3D problem
```
./asgard -p continuity3 -l 5  -d 4
```
Large 3D problem
```
./asgard -p continuity3 -l 10  -d 8
```
Small 6D problem
```
./asgard -p continuity -l 4 -d 4
```
Large 6D problem
```
./asgard -p continuity -l 6 -d 4
```

**Comment by bmcdanie** [comment]
will do

**Comment by bmcdanie** [comment]
https://github.com/project-asgard/asgard/wiki/profiling#sample-problem-sizes does this work for you @dlg0 ? Let me know if this works or there are more things you want for this.

**Comment by bmcdanie** [comment]
done!
