### ISSUE TITLE
fault tolerance strategy

### ISSUE THREAD

**Issue by grahamlopez** [project-asgard/asgard#32]
ASGarD
    asgardasgard
    Issues
    #32

Open
Opened 4 months ago by Graham Lopez
Close issue
New issue
fault tolerance strategy

Tyler and I started brainstorming about some fault tolerance approaches. Let's gather our thoughts and discussion here in this issue.

    simple checkpointing (full application restart).
        probably start with this as it's expected to be easier to implement
        need to snapshot: full input vector from previous timestep
        possibly need adaptivity information

    per-node failure handling (online recovery)
        if a node fails, we only need to recompute deg*dim sized segment of the input vector
        no specific thoughts yet about rebalancing strategies

Related issues
0

Graham Lopez
Graham Lopez @bgl · 4 months ago
Owner
Another thing to consider is library support (if any). HDF5, other?

**Comment by mkstoyanov** [comment]
Stale issue, open a new one, if still relevant.
