### ISSUE TITLE
library dependency collision

### ISSUE THREAD

**Issue by stonecoldhughes** [project-asgard/asgard#323]
When building Asgard with:

`mkdir build; cd build;`
`cmake -DASGARD_IO_MATLAB_DIR=/path/to/MATLAB -DASGARD_USE_CUDA=ON ..`

This error message is generated by CMake:

Cannot generate a safe runtime search path for target io-tests because
files in some directories may conflict with libraries in implicit directories:
runtime library [libcublas.so.10] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
/usr/local/MATLAB/R2019b/bin/glnxa64
Some of these libraries may not be found correctly.

**Comment by bmcdanie** [comment]
I'm not sure your implementation, but I'd try linking to your MATLAB libs with the absolute path, and not adding MATLAB lib directory to the search path.

or, try linking matlab libs last. this is not code in develop, correct?

**Comment by bmcdanie** [comment]
closing - this issue does not reference code in ASGarD develop. let me know if the above solutions don't work and we can work through the PR.
