### ISSUE TITLE
Find/link to ESSL

### ISSUE THREAD

**Issue by bmcdanie** [project-asgard/asgard#327]
Currently, `contrib/contrib.cmake` locates BLAS/LAPACK by first 1) searching user supplied paths or 2) generic cmake `find_library` call. Both options look for libraries named `blas` / `lapack` or `openblas`. Extend these methods to find ESSL, either by using CMake FindBLAS/FindLAPACK (ideal) or extending the library names we search for. In either case, need to test that our Cray wrapper fixes still work.

**Comment by mkstoyanov** [comment]
Stale issue, open a new one, if still relevant.
