### ISSUE TITLE
Loosen test tolerances to pass with different libraries/systems

### ISSUE THREAD

**Issue by bmcdanie** [project-asgard/asgard#328]
Our test tolerances for floating point comparisons are currently set to the tightest order of magnitude for which the tests still pass on Fusiont5 CI. This was a problem when moving to the hackathon systems, which used different libraries/architectures. Possible solution: loosen tolerances by one order of magnitude?

**Comment by quantumsteve** [comment]
We've reduced tolerances several times to account for different libraries and architectures. Hoping this is a less common issue going forward. 

Stale issue, open a new one, if still relevant.
