### ISSUE TITLE
performance regression testing

### ISSUE THREAD

**Issue by grahamlopez** [project-asgard/asgard#33]
ASGarD
    asgardasgard
    Issues
    #33

Open
Opened 4 months ago by Graham Lopez
Close issue
New issue
performance regression testing

we will want an automated way to detect and measure performance regressions
Related issues
0

Related merge requests
1

    Feature/mem tracking
    asgard/asgard !85

Graham Lopez @bgl added testing label 4 months ago
Graham Lopez @bgl added help_wanted label 3 months ago
Graham Lopez @bgl assigned to @bgl 1 month ago
Graham Lopez
Graham Lopez @bgl · 1 week ago
Owner

once we get !85 (merged), we can probably start on this informally by just keeping a record of the data recorded in order to generate the runtime estimates

**Comment by mkstoyanov** [comment]
Seems complete, reopen if further work is needed.
