### ISSUE TITLE
Clean assert disable

### ISSUE THREAD

**Issue by bmcdanie** [project-asgard/asgard#330]
Our previous (CPU-only) performance measurements for asserts vs. no asserts indicated little or no penalty.

However, during the hackathon, we noted that disabling asserts greatly impacts kernel performance. This makes sense - resources (e.g. registers) used to set up asserts can be expensive in that context. 

Add macros or some other mechanism whereby we can disable asserts without seeing dozens of unused variable warnings.

**Comment by quantumsteve** [comment]
assert have been replaced with the expect macro, so it should be easy to override with a CMake flag.
https://github.com/project-asgard/asgard/blob/d43b3bdaf64db8385d5035f558acad7683ad59cf/src/tools.hpp#L16
