### ISSUE TITLE
templating gemm parameters/unrolling k (kronmult)

### ISSUE THREAD

**Issue by bmcdanie** [project-asgard/asgard#332]
one of our last hackathon performance improvements to the main kronmult kernels (`kronmult[dim]_xbatched`) relied on constant `m`, `n`, `k` parameters to gemm device functions `kgemm_n[n/t]`. this allows the compiler to unroll the innermost `k` loop, and sometimes the `m`, `n` blocking loops as well. these improvements yielded a marginal improvement for our benchmark 6d problem (lev 2 deg 2). 

all of the other hackathon improvements have been added to the code. we tried to perform similar unrolling without the need for non-type templates using a switch statement/macros. performance testing on ascent shows similar (slightly worse) performance to the template unroll `k` used during the hackathon, but doesn't give us `constexpr` `m`/`n`. 

the hackathon code used shortcuts (e.g. hardcoding degree to the degree of the benchmark problem) to avoid the need to template all the way up the call stack to evaluate the technique. so, if we want the last little speedup (e.g. 72 vs 82ms on the benchmark problem), we will need to explore extending `m`,`n`,`k` templating within kronmult.

**Comment by quantumsteve** [comment]
Stale issue, open a new one, if still relevant.

We're currently focused on adding documentation and functionality. We'd likely try bringing in [kronmult993](https://github.com/project-asgard/kronmult993) before extensively refactoring kronmult.
