### ISSUE TITLE
standardize namespace usage

### ISSUE THREAD

**Issue by bmcdanie** [project-asgard/asgard#335]
new components have component-level namespaces named for the component. standardize across components.

**Comment by quantumsteve** [comment]
The `fk` namespace in tensor.hpp is confusing (we traced it back to an earlier name for this project?). Can any refactoring tools do the heavy lifting?

**Comment by mkstoyanov** [comment]
It is confusing, but I would be careful with such refactoring. Clutters the git history and can create a ton of issues.

Do we know if we have external users, maybe we can add a new namespace but keep the old as a fallback and backwards compatibility.

**Comment by quantumsteve** [comment]
I wanted to make a note of the confusion at our last meeting, but also agree a namespace change could generate confusion without adding functionality.

We've had external collaborators in the past, but I'm not aware of any current external users.

**Comment by quantumsteve** [comment]
An `agard::` namespaces was created in #465.
