### ISSUE TITLE
tests binary is not relocatable

### ISSUE THREAD

**Issue by grahamlopez** [project-asgard/asgard#34]
ASGarD
    asgardasgard
    Issues
    #34

Open
Opened 4 months ago by Graham Lopez
Close issue
New issue
tests binary is not relocatable

We need to have CMake substitute in the full path to the {source_repo}/testing directory in order to support out-of-tree builds.

Because we hardcode paths to the golden input values (generated from matlab) for many of our tests, the testing binary is not very relocatable.
Related issues
0

    Graham Lopez @bgl added help_wanted label 3 months ago
    Graham Lopez @bgl assigned to @bgl 1 month ago
    Graham Lopez
Graham Lopez @bgl · 1 week ago
Owner
this can probably be fixed with WORKING_DIRECTORY now that we are using ctest
Graham Lopez @bgl added someday label 5 days ago

**Comment by mkstoyanov** [comment]
Good point, it was fixed recently.
