### ISSUE TITLE
direct solve using inverted 1d matrices for implicit stepping

### ISSUE THREAD

**Issue by bmcdanie** [project-asgard/asgard#340]
given this property:

![Screenshot from 2020-09-02 08-57-44](https://user-images.githubusercontent.com/7290188/91988417-3d723f80-ecfd-11ea-8b70-cc941a226172.png)

It seems possible to perform an implicit timestep, which requires a solve of the large sparse system matrix, by inverting the (relatively) small, dense 1d coefficient matrices, then running @efdazedo 's `kronmult` code to perform the required Kronecker product and gemv. Just as in the explicit timestepping case, the hash table would provide information about which elements to compute on/ignore given the sparse grid.

@efdazedo , @dlg0 what do you think of this technique?

**Comment by efdazedo** [comment]
Hi Tyler,

You are correct that solve y = kron(A,B)*x  to find x as    x =  inv(kron(A,B))*y  = kron( inv(A), inv(B))*y

X = kron( inv(A),inv(B))*y,   evaluated as.  X = inv(B) * Y * transpose( inv(A))
Or

  1.  W = B\Y, (2) X = W/(transpose(A))

There is a fast solver for sum of 2 kronecker products


If C = kron(A1,B1) + kron(A2,B1), then there is a fast method by generalized eigen decomposition of the pairs (A1,A2),  and (B1,B2).  To find Ua, Va,  and Ub, Vb. There. Ua * A1 *Va is Da1 diagonal, Ua * A2 * Va is Da2 diagonal,   Ub * B1 * Vb is Db1 diagonal, Ub * B2 * Vb is Db2 diagonal

Then solve.  C * x  = y = {kron(A1,B1) + kron(A2,B2)} * y
Kron(Ua,Ub) * C * kron(Va,Vb) * inv( kron(Va,Vb) ) * x = kron(Ua,Ub)*y
{Kron( Da1,Db1) + kron(Da2,Db2) } * xhat = yhat …. (*)

where
Kron(Va,Vb)*xhat = x
Yhat = kron(Ua,Ub)*y

And { kron(Da1,Db1) + kron(Da2,Db2)}. Is a diagonal matrix, so solving (*) is easy.
There are separate questions about numerical stability and conditioning of Ua,Ub,Va,Vb

I am not aware of fast solver for more general sum of 3 or more Kronecker products.
This may be an interesting “open” question.


If a matrix C = kron(A1,B1) + … + kron(Ak,Bk)  is sum of  several  Kronecker products, it may be reasonable to consider the inverse of each single or pair of Kronecker products  as a preconditioner.

Ed

**Comment by quantumsteve** [comment]
Stale issue, open a new one, if still relevant.

I'd love to remove the dense matrix from the implicit solver, but don't think it is a near-term priority.
