### ISSUE TITLE
renamed PDEs

### ISSUE THREAD

**Issue by bmcdanie** [project-asgard/asgard#344]
sync up fokkerplanck PDEs in C++ with renames to the MATLAB versions.

`fokkerplanck1_4p1a -> fokkerplanck1_pitch_E(1)` ,
`fokkerplanck1_4p1b -> fokkerplanck1_pitch_E(2)` , 
`fokkerplanck1_4p2-> fokkerplanck1_pitch_C`

**Comment by hbrunie** [comment]
@bmcdanie @dlg0 @lwonnell There is a difference between the description in the comment and the actual code I think.
The description on top shows:
`df/dt == d/dz ( (1-z^2) df/dz )` [code](https://github.com/project-asgard/asgard/blob/fa93c944f803b45367cf65c17337155104259c66/src/pde/pde_fokkerplanck1_4p1a.hpp#L20)
But the description in the [Matlab code](https://github.com/project-asgard/DG-SparseGrid/blob/20448e62cfb796cbc50ba721cc04821105301e56/PDE/fokkerplanck1_pitch_E.m#L3)  shows `df/dt == -d/dz ( (1-z^2)f`. Notice the sign is different and f is not derived.
But in [code](https://github.com/project-asgard/asgard/blob/fa93c944f803b45367cf65c17337155104259c66/src/pde/pde_fokkerplanck1_4p1a.hpp#L145) the description is different. Same file but different comment. They should tell the same story I think. Which one is correct?

**Comment by hbrunie** [comment]
Here is the branch corresponding to the changes I am making to solve this issue: [branch](https://github.com/hbrunie/asgard/tree/renamepde)

**Comment by dlg0** [comment]
```
fokkerplanck1_4p1a -> fokkerplanck1_pitch_E (case=1) 
fokkerplanck1_4p1b -> fokkerplanck1_pitch_E (case=2) ** this is a good adaptivity test case
fokkerplanck1_4p2-> fokkerplanck1_pitch_C
fokkerplanck1_4p3-> fokkerplanck1_pitch_R
```

It looks like the C++ does not have `_4p1b` so we will need to add it. It is a very minor variant of `_4p1a` and I'd like to add the `case` ability as we have in the matlab as a command line option in the C++, so this seems a good opportunity to do that?

@bmcdanie @hbrunie

**Comment by hbrunie** [comment]
Yes I'm on it. The pr I'm building will contain a new option to choose the pde case (1 by default). So on long term for each pde we will be able to add new cases.
But @dlg0 you did not answer about the difference between the PDE in matlab and the one in C++.
The description on top shows:
df/dt == d/dz ( (1-z^2) df/dz ) code, but the description in the Matlab code shows df/dt == -d/dz ( (1-z^2)f.
Which one is the right one?

**Comment by dlg0** [comment]
It looks to me like in `src/pde/pde_fokkerplanck1_4p1a.hpp` the actual PDE coding matches the matlab, but the comment is a copy and paste error - so the matlab comment is correct, the C++ comment is incorrect. You can confirm this by noting only one `grad` operator, whereas anything of the form `d/dz df/dz` would have two.
