### ISSUE TITLE
Independant Floating point precision for analytic solution

### ISSUE THREAD

**Issue by hbrunie** [project-asgard/asgard#352]
**Problem:**
Currently changing ASGARD_USE_DOUBLE_PREC from ON to OFF changes both the numerical and analytical solutions from double to float.

**Goal:**
Make the analytical solution floating point precision independent from the numerical solution computation.
Thus ASGARD_USE_DOUBLE_PREC compiler flag will only impact the numerical solution computation.
Analytic solution will always be computed with analytic_solv_prec (double by default)

**Solution:**
Change make_PDE. We want just one PDE.
**but** be able to generate `basis::wavelet_transform<P, resource::host>` in both float and double from the same pde object. Same for `transform_and_combine_dimensions` and `generate_all_coefficients<P>(*pde, transformer)`

**Alternative solution**
Use 2 instances of pde: make_PDE<P> and make_PDE<analytic_soln_prec>
2 instances of wavelet transform (one with each pde). Then no need to change either `transform_and_combine_dimensions` nor `generate_all_coefficients<P>(*pde, transformer)`.

**Comment by hbrunie** [comment]
@bmcdanie you mentioned that using 2 pde works fine now because the coefficient generation is made outside of the constructor, but in the future this should be made differently and thus the solution with 1 pde is preferable right?

**Comment by quantumsteve** [comment]
Stale issue, open a new one, if still relevant.
