### ISSUE TITLE
Common parameters and functions file for use across multiple PDEs

### ISSUE THREAD

**Issue by dlg0** [project-asgard/asgard#354]
In the matlab we have `pdename-parameters.m` like files which allow for the re use of code across common PDEs. `PDE/mirror_parameters.m` is an example in the DG-SparseGrid repo. I'd like this capability within the C++ also. 

Note that one thing I'm thinking about here is that we might want to move to an approach where both the Matlab and the C++ can parse a the same type of input file, then we'd avoid the "translation" from Matlab to C++ we have now. Just something to keep in mind when dealing with the above issue.

**Comment by mkstoyanov** [comment]
matlab is deprecated and the C++ pdes are being reworked to allow more flexible initialization
