### ISSUE TITLE
Evaluate options for autogenerated documentation

### ISSUE THREAD

**Issue by bmcdanie** [project-asgard/asgard#360]
while we have some high-level descriptions of the code in the repo wiki, it may be helpful to use a tool like Doxygen (https://www.doxygen.nl/index.html) or similar to automatically generate source code documentation.

we need to look at our options, then select a tool and begin the process of documenting the source.

**Comment by mkstoyanov** [comment]
We have the basic web-page now, we need to move on with the docs:
- [x] add doxygen to the build system
- [x] establish policy that all new code has to be documented
- [ ] use doxygen groups, add sensible modules and add each class/method to an appropriate module
    * the groups/modules are a good way to organize the docs, the code is already organized in modules
    * when you add new code, you have already gone through the process of thinking, it's easy to add documentation
- [ ] add documentation for the core classes (most critical or most commonly used)
- [ ] work on filling the rest (grind work, do it gradually)

**Comment by mkstoyanov** [comment]
we need to stabilize the code some more before we can come back to this one

although @quantumsteve  has also made significant progress in several modules
