### ISSUE TITLE
Build faster for PDE development

### ISSUE THREAD

**Issue by dlg0** [project-asgard/asgard#365]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I am developing a new PDE and every time I recompile after only changing the PDE file it rebuilds almost everything.

**Describe the solution you'd like**
When I rebuild a slightly modified PDE, it only has to rebuild the PDE file, and perhaps some other minor thing, i.e., be faster.

**Comment by bmcdanie** [comment]
note to self - move definitions into header, implementation into .cpp, and explicitly instantiate needed class templates.
