### ISSUE TITLE
calculate moment integral

### ISSUE THREAD

**Issue by bmcdanie** [project-asgard/asgard#366]
I don't know what this is, but the MATLAB has it, and we need it in the C++: https://github.com/project-asgard/DG-SparseGrid/blob/20448e62cfb796cbc50ba721cc04821105301e56/asgard_run_pde.m#L109.

These may also require implementing jacobian functions in dimension class: https://github.com/project-asgard/DG-SparseGrid/blob/20448e62cfb796cbc50ba721cc04821105301e56/PDE/mirror3.m#L38.

Default jacobian seems to be: https://github.com/project-asgard/DG-SparseGrid/blob/20448e62cfb796cbc50ba721cc04821105301e56/DIMENSION.m#L10,

**Comment by dlg0** [comment]
The `moment_integral` in the matlab takes as input the real space solution and calculates the integral of some function times that solution, i.e., "takes a moment".
