### ISSUE TITLE
Adaptivity does not improve solution on fokkerplanck_pitch_E/4p1a case 2

### ISSUE THREAD

**Issue by hbrunie** [project-asgard/asgard#370]
**Describe the bug**
On Matlab adaptivity improve error on fokkerplanck_pitch_E case 2 (thresh 0.1, dt 0.01)
On ASGARD the error does not improve as much.
*Also something must be computed differently between Asgard and DG-SparseGrid as the result (even without adaptivity) are quite different*. This may be due to my update of `fokkerplanck_pitch_E/4p1a` to build *case 2*. I have just changed `f0`, you can take a look at [the PR on renaming](https://github.com/project-asgard/asgard/pull/368/commits/f5d3447c7ffd069fc250d97617ca7a4a52591698#diff-cd306135901b4db9043c48dc8b5af06fd9d3fda16a9b722cf5e0a1ff873f0456R80). [1]
This change can be seen in the last commit of [this branch case2](https://github.com/hbrunie/asgard/tree/case2) (rebased on develop) 

Without adaptivity
```
Errors for local rank: 0
RMSE (numeric-analytic) [wavelet]: 0.0879229
Relative difference (numeric-analytic) [wavelet]: 45.6539 %
timestep: 49 complete
```

With adaptivity
```
 adapt -- coarsened grid from 18 -> 12 elems
 adapt -- refined grid from 12 -> 18 elems
 adapt -- refined grid from 18 -> 18 elems
Errors for local rank: 0
RMSE (numeric-analytic) [wavelet]: 0.0839855
Relative difference (numeric-analytic) [wavelet]: 43.6095 %
timestep: 49 complete
```

On the contrary with Matlab:
Without adaptivity
```
Step 50 of 50 at 0.490000 seconds
    Calculate time dependent matrix coeffs
    Time step (dt=0.01)
    num_dof : 32
    wavelet space absolute err : 0.022722
    wavelet space relative err : 9.4654 %
t: 0.49
dt: 0.01
    real space absolute err : 0.095054
    real space relative err : 7.5358 %
```

With adaptivity
```
No more adaption needed - advancing time
    t = 0.49
    num_dof : 36
    wavelet space absolute err : 0.005543
    wavelet space relative err : 2.3091 %
t: 0.49
dt: 0.01
    real space absolute err : 0.023757
    real space relative err : 1.8683 %
```

**To Reproduce**
1. branch reference on DG-SparseGrid commit 20448e62cfb796cbc50ba721cc04821105301e56
2. branch develop on ASGARD, just change the `f0` from fokkerplanck_4p1a as shown at the bottom of this page [1]. 
3.`asgard(@fokkerplanck1_pitch_E,'lev',4,'deg',2,'timestep_method','RK3','dt',0.01,'num_steps',50,'case',2,'save_output',true,'calculate_mass',false,'adapt_initial_condition',true,'adapt_threshold',1e-1,'adapt',true)`
4. `asgard(@fokkerplanck1_pitch_E,'lev',4,'deg',2,'timestep_method','RK3','dt',0.01,'num_steps',50,'case',2,'save_output',true,'calculate_mass',false,'adapt_initial_condition',true,'adapt_threshold',1e-1,'adapt',false)`
5. `./asgard -p fokkerplanck_1d_4p1a -n 50 -d 2 -l "4" -t 0.01`
6. `./asgard -p fokkerplanck_1d_4p1a -n 50 -d 2 -l "4" -t 0.01 --adapt --thresh 0.1`
 

**Expected behavior**
It is expected that errors should be "similar" between C++ and Matlab code.

**System:**
 - On Cori
 - modules:
 ```
Currently Loaded Modulefiles:
  1) cce/9.1.0                                         9) gni-headers/5.0.12.0-7.0.1.1_6.32__g3b1768f.ari  17) cmake/3.18.2
  2) craype/2.6.2                                     10) xpmem/2.2.20-7.0.1.1_4.14__g0475745.ari          18) esslurm
  3) craype-network-aries                             11) job/2.2.4-7.0.1.1_3.41__g36b56f4.ari             19) cgpu/1.0
  4) cray-libsci/19.06.1                              12) dvs/2.12_2.2.164-7.0.1.1_13.1__g354a5276         20) jdk/1.8.0_202
  5) udreg/2.3.2-7.0.1.1_3.38__g8175d3d.ari           13) alps/6.6.58-7.0.1.1_6.10__g437d88db.ari          21) cuda/10.2.89
  6) ugni/6.0.14.0-7.0.1.1_7.40__ge78e5b0.ari         14) rca/2.2.20-7.0.1.1_4.53__g8e3fb5b.ari            22) gcc/8.3.0
  7) pmi/5.0.14                                       15) atp/2.1.3
  8) dmapp/7.1.1-7.0.1.1_4.54__g38cf134.ari           16) PrgEnv-cray/6.0.5
```
For Matlab only
`matlab/R2019a`
**Additional context**
[1]
```
static P f0(P const z, int select = case_selection_)
   {
       P sig = (P)0.1;
       switch(select)
       {
           case 1:
               return z * 0. + 1;
               break;
           case 2:
               return exp(-((std::pow(z,2))/(std::pow(sig,2))));
               break;
           default:
               std::cerr << "Pick a correct case for PDE."<< std::endl;
               exit(-1);
               break;
       }
       return -1.;
   }

```

**Comment by mkstoyanov** [comment]
Fixed in #709 fixed the time issue with `(i+1) * dt` vs. `i * dt`
