### ISSUE TITLE
Clang format changing between llvm 8.0 and 9.0

### ISSUE THREAD

**Issue by hbrunie** [project-asgard/asgard#371]
**Describe the bug**
When using the clang-format binary (inside the script `./testing/automated/clang-format-check.sh`)
The result on `tensors.hpp` is not the same between my local machine (Cori llvm-9.0) and the CI on AWS (we are using llvm-7.0).

Nevertheless, `.clang-format` should specify the source code wanted completely, and thus we should not have reproducibility issues.

**Comment by bmcdanie** [comment]
ouch - apparently, getting consistent output across clang-format versions is nontrivial: https://stackoverflow.com/questions/59395507/how-to-maintain-a-clang-format-file-for-different-clang-format-versions.

**Comment by hbrunie** [comment]
We can update the CI to llvm-9.0.0 and oblige people to code with recent llvm versions?

**Comment by bmcdanie** [comment]
I think this is the best solution - update the CI llvm and require clang-format with same version.

**Comment by quantumsteve** [comment]
We're currently using clang-format-12.

Stale issue, open a new one, if still relevant.
