### ISSUE TITLE
nonseparable (time+space) boundary conditions

### ISSUE THREAD

**Issue by bmcdanie** [project-asgard/asgard#374]
the current code assumes separable boundary conditions.

"unscaled" boundary condition vectors are created with some time `t`, and later scaled with `bc_time_func(t2)`. I am not convinced this will yield the correct answer when the boundary condition vectors actually use the initial time `t`.

**Comment by hbrunie** [comment]
What is the link between the fact that `BC` are assumed separable, and the fact that the correct answer may not be yield when BC use initial time `t`?

**Comment by mkstoyanov** [comment]
The #699 interpolation framework is the right path forward for non-separable functions and operators.
