### ISSUE TITLE
add enable FE EXCEPT / static analysis to debug build

### ISSUE THREAD

**Issue by bmcdanie** [project-asgard/asgard#381]
This would require us to track down any current proliferation of NANs inside the code.

Additionally, look into compile-time methods to enable FE except trapping?

Look into low-overhead static analysis tools in debug build.

**Comment by dlg0** [comment]
Runtime checking on the floating point checking would be ok too?

**Comment by bmcdanie** [comment]
Yes, I think so, I just wanted to check for compiler flags for that as well.

**Comment by mkstoyanov** [comment]
stale
