### ISSUE TITLE
Continuity 6D: error constant or decreases slightly

### ISSUE THREAD

**Issue by hbrunie** [project-asgard/asgard#386]
**Describe the bug**

PDE continuity_6, lev 2, degree >=6, error is almost constant.
with degree 8 the error decreases.

This is not an expected behavior.

**To Reproduce**
On GPU Volta V100 on Cori
1. develop branch
2. double precision, no MPI, OpenMP ON (but 1 thread)
3. ./asgard -p continuity_6 -n 20 -d 8 -l "2 2 2 2 2 2" 
4. default dt

**Expected behavior**

**System:**
 - Cori GPUs V100
 - modules 
    - module purge
    -  module load PrgEnv-cray cmake/3.18.2 cray-libsci cray-mpich  cray-python/3.8.5.0 cgpu cuda

**Comment by quantumsteve** [comment]
Cori will be retired soon. Does the same issue appear on Perlmutter?
