### ISSUE TITLE
implicit conversion

### ISSUE THREAD

**Issue by hbrunie** [project-asgard/asgard#393]
**Describe the bug**
Some warnings do not show with current compiler flags
I suggest we add  -float-conversion  in
string(APPEND CMAKE_CXX_FLAGS " -Wall -Wextra -Wpedantic")

in order to catch all the implicit conversion, which could create bugs depending on what we do.

**Comment by mkstoyanov** [comment]
Assigning flags directly into CMake is bad practice, we have the flags enabled in the CI and developers should enable those locally in their workstations. CMake should be free from flags and allow the user to set their own.
