### ISSUE TITLE
MPI Deadlock in CI tests for num processors less than 4

### ISSUE THREAD

**Issue by cianciosa** [project-asgard/asgard#404]
**Describe the bug**
On the GitHub actions Mac instances, the number of available processors is limited to 2. Recent version of OpenMPI have made it an error to request more MPI processes than the number of hardware threads unless the oversubscribe flag is use. To implement  a unit test case I have used the MPIEXEC_NUM_PROC flag from the findMPI package to limit the number of MPI processes if the number of cores is less than 4. This causes a MPI process to deadlock in the 

distribution-test-mpi
https://github.com/cianciosa/asgard/runs/3688391328?check_suite_focus=true

for debug builds and

adapt-test-mpi
https://github.com/cianciosa/asgard/runs/3688391280?check_suite_focus=true
for release builds.

**To Reproduce**
0. Clone cianciosa asgard fork.
1. git commit hash being built https://github.com/cianciosa/asgard/commit/582aa5f86e65825ff065c5fd5380fbdb36174037
2. cmake command https://github.com/cianciosa/asgard/blob/582aa5f86e65825ff065c5fd5380fbdb36174037/.github/workflows/ci_scalapack.yaml#L24
3. full program/test invocation command mpirun -n 3 ./distribution_tests
4. additional steps 

**Expected behavior**
Either the tests run fine but slower with less processors or an error message is returned stating these tests require 4 processes.

**System:**
 - system name Github actions
 - modules loaded N/A libscalapack was installed via homebrew
 - other systems where this is reproducible My laptop for when run with 3 processors.

**Additional context**
On my laptop with two processors, nothing hangs but there are several test failures. None of the tests fail when the number of MPI processes is 4. Scalapack mac ci test was added because there was a compiler error that prevented mac builds using the Accelerate library from compiling.

**Comment by cianciosa** [comment]
The default constructor is getting called after `initialize_distribution` which is resetting the `distro_handle.global_comm` back to `MPI_COMM_WORLD`. Debugging messages set in `initialize_distribution` and `distribution_handler` show this happening.

```
initialize_distribution rank 0 global_comm 0x7f8f51c56ae0 world_comm 0x10faea590
set global comm on world rank 0 comm rank 0
initialize_distribution rank 1 global_comm 0x7ff0cb44dc90 world_comm 0x106b4f590
set global comm on world rank 1 comm rank 1
initialize_distribution rank 2 global_comm 0x103961990 world_comm 0x103961590
Constructing new distribution_handler on rank 2 global_comm 0x103961590 world_comm 0x103961590
Constructing new distribution_handler on rank 0 global_comm 0x10faea590 world_comm 0x10faea590
Constructing new distribution_handler on rank 1 global_comm 0x106b4f590 world_comm 0x106b4f590
```

**Comment by mkstoyanov** [comment]
Tests with 2 and 3 ranks are passing currently.
