### ISSUE TITLE
Exception from wavelet to realspace transform if multiple MPI ranks

### ISSUE THREAD

**Issue by mtbc** [project-asgard/asgard#413]
**Describe the bug**
Turning MATLAB on and running with multiple ranks causes the first `wavelet_to_realspace` in `main.cpp` to throw an exception due to access beyond the vector size in creating a view of a section of the wave space vector. May be related to #182.

**To Reproduce**
1. Build from `8174ce0c` with `ASGARD_USE_MATLAB` set.
1. `mpirun -n 2 ./asgard`
1. Observe the exception.

**Expected behavior**
The computation to run without throwing an exception, just as it does with `mpirun -n 1 ./asgard`

**System:**
Local Ubuntu 20.04 Linux laptop with GNU toolchain and CMake 3.21.1.

**Comment by mtbc** [comment]
```
asgard: /home/6t4/src/asgard/src/tensors.hpp:1572: fk::vector<P, mem, resrc>::vector(const fk::vector<P, omem, resrc>&, int, int, bool) [with mem_type m_ = mem_type::const_view; <template-parameter-2-2> = void; mem_type omem = mem_type::owner; P = double; mem_type mem = mem_type::const_view; resource resrc = resource::host]: Assertion `stop_index < vec.size()' failed.
```

**Comment by mkstoyanov** [comment]
closing stale issue, possibly outdated
