### ISSUE TITLE
Allow table size < num ranks in MPI

### ISSUE THREAD

**Issue by ckendrick** [project-asgard/asgard#419]
When the table size is less than the number of MPI ranks, the code will exit. This can happen for certain problems when adaptivity is enabled which happens much more frequently when the [minimum level for coarsening was recently changed](https://github.com/project-asgard/asgard/blob/97eb56d9f0d0bafcf3ba9e601724c4c1962716ec/src/adapt.cpp#L269).

Asgard should be adjusted to handle this case without exiting. Refer to where this is triggered in [adapt.cpp](https://github.com/project-asgard/asgard/blob/97eb56d9f0d0bafcf3ba9e601724c4c1962716ec/src/adapt.cpp#L338-L342) and [when retrieving the subgrid in distribution.cpp](https://github.com/project-asgard/asgard/blob/97eb56d9f0d0bafcf3ba9e601724c4c1962716ec/src/distribution.cpp#L190).

There are several tests that have been disabled to get around this problem. They should be re-enabled when this is fixed.

**Comment by mkstoyanov** [comment]
We should have limits and how much we coarsen and the MPI work will have to done in a rework coupled with other methods.
