### ISSUE TITLE
ideas to improve PDE spec understandability

### ISSUE THREAD

**Issue by grahamlopez** [project-asgard/asgard#42]
ASGarD
    asgardasgard
    Issues
    #42

Open
Opened 3 months ago by Green, David L
Close issue
New issue
ideas to improve PDE spec understandability

The PDE spec could be a little more human readable. This may be as simple as turning off the clang formatting within these to allow for things like ...

  // define sources
  
  // source 0
  inline static std::vector<vector_func<P>> const source0_funcs = {&PDE_continuity_3::source_0_dim0, &PDE_continuity_3::source_0_dim1,&PDE_continuity_3::source_0_dim2};
  inline static scalar_func<P> const source0_time = &PDE_continuity_3::source_0_time;
  inline static source<P> const source0 = source<P>(source0_funcs, source0_time);

  // source 1
  inline static std::vector<vector_func<P>> const source1_funcs = {&PDE_continuity_3::source_1_dim0, &PDE_continuity_3::source_1_dim1,&PDE_continuity_3::source_1_dim2};
  inline static scalar_func<P> const source1_time = &PDE_continuity_3::source_1_time;
  inline static source<P> const source1 = source<P>(source1_funcs, source1_time);

  // source 2
  inline static std::vector<vector_func<P>> const source2_funcs = {&PDE_continuity_3::source_2_dim0, &PDE_continuity_3::source_2_dim1,&PDE_continuity_3::source_2_dim2};
  inline static scalar_func<P> const source2_time = &PDE_continuity_3::source_2_time;
  inline static source<P> const source2 = source<P>(source1_funcs, source2_time);

  // source 3
  inline static std::vector<vector_func<P>> const source3_funcs = {&PDE_continuity_3::source_3_dim0, &PDE_continuity_3::source_3_dim1,&PDE_continuity_3::source_3_dim2};
  inline static scalar_func<P> const source3_time = &PDE_continuity_3::source_3_time;
  inline static source<P> const source3 = source<P>(source3_funcs, source3_time);

  // store PDE functions/information in members
  inline static std::vector<dimension<P>> const dimensions = {dim0, dim1, dim2};
  inline static term_set<P> const terms                    = {terms0, terms1, terms2};
  inline static std::vector<source<P>> const sources       = {source0, source1,source2, source3};

yes, there are some long lines (although see next point), but readabiliy may trump lone lines?

and then also, do we have to use the &PDE_continuity_3:: qualifier? (I would have though being defined with the class itself means we don't need that? i.e.,

  // define sources
  
  // source 0
  inline static std::vector<vector_func<P>> const source0_funcs = {&source_0_dim0, &source_0_dim1,&source_0_dim2};
  inline static scalar_func<P> const source0_time = &source_0_time;
  inline static source<P> const source0 = source<P>(source0_funcs, source0_time);

  // source 1
  inline static std::vector<vector_func<P>> const source1_funcs = {&source_1_dim0, &source_1_dim1,&source_1_dim2};
  inline static scalar_func<P> const source1_time = &source_1_time;
  inline static source<P> const source1 = source<P>(source1_funcs, source1_time);

  // source 2
  inline static std::vector<vector_func<P>> const source2_funcs = {&source_2_dim0, &source_2_dim1,&source_2_dim2};
  inline static scalar_func<P> const source2_time = &source_2_time;
  inline static source<P> const source2 = source<P>(source1_funcs, source2_time);

  // source 3
  inline static std::vector<vector_func<P>> const source3_funcs = {&source_3_dim0, &source_3_dim1,&source_3_dim2};
  inline static scalar_func<P> const source3_time = &source_3_time;
  inline static source<P> const source3 = source<P>(source3_funcs, source3_time);

  // store PDE functions/information in members
  inline static std::vector<dimension<P>> const dimensions = {dim0, dim1, dim2};
  inline static term_set<P> const terms                    = {terms0, terms1, terms2};
  inline static std::vector<source<P>> const sources       = {source0, source1,source2, source3};

and perhaps another suggestion, ... can we clump the construction of dimensions, terms, and sources seperately as in the matlab, i.e.,

  // define dimensions

  // dim0
  static boundary_condition constexpr dim0_BCL = boundary_condition::periodic;
  static boundary_condition constexpr dim0_BCR = boundary_condition::periodic;
  static P constexpr dim0_min                  = -1.0;
  static P constexpr dim0_max                  = 1.0;
  static int constexpr dim0_level              = 2;
  static int constexpr dim0_degree             = 2;
  inline static vector_func<P> const dim0_initial_condition = &initial_condition_dim0;
  static auto constexpr dim0_name = "x";
  inline static dimension<P> const dim0 = dimension<P>(dim0_BCL, dim0_BCR, dim0_min, dim0_max, dim0_level, dim0_degree, dim0_initial_condition, dim0_name);

  // dim1
  static boundary_condition constexpr dim1_BCL = boundary_condition::periodic;
  static boundary_condition constexpr dim1_BCR = boundary_condition::periodic;
  static P constexpr dim1_min                  = -2.0;
  static P constexpr dim1_max                  = 2.0;
  static int constexpr dim1_level              = 2;
  static int constexpr dim1_degree             = 2;
  inline static vector_func<P> const dim1_initial_condition = &initial_condition_dim1;
  static auto constexpr dim1_name = "y";
  inline static dimension<P> const dim1 = dimension<P>(dim1_BCL, dim1_BCR, dim1_min, dim1_max, dim1_level, dim1_degree, dim1_initial_condition, dim1_name);

  // dim3
  static boundary_condition constexpr dim2_BCL = boundary_condition::periodic;
  static boundary_condition constexpr dim2_BCR = boundary_condition::periodic;
  static P constexpr dim2_min                  = -3.0;
  static P constexpr dim2_max                  = 3.0;
  static int constexpr dim2_level              = 2;
  static int constexpr dim2_degree             = 2;
  inline static vector_func<P> const dim2_initial_condition = &initial_condition_dim2;
  static auto constexpr dim2_name = "z";
  inline static dimension<P> const dim2 = dimension<P>(dim2_BCL, dim2_BCR, dim2_min, dim2_max, dim2_level, dim2_degree, dim2_initial_condition, dim2_name);

  // assemble dimensions
  inline static std::vector<dimension<P>> const dimensions = {dim0, dim1, dim2};

  
  // define terms

  // term0

  // term0 dim0
  static coefficient_type constexpr term0_dim0_type  = coefficient_type::grad;
  inline static g_func_type<P> const term0_dim0_func = &g_func_identity;
  static bool constexpr term0_dim0_time_dependent = false;
  inline static fk::vector<P> const term0_dim0_data; // empty in this case
  static flux_type constexpr term0_dim0_flux = flux_type::central;
  static auto constexpr term0_dim0_name      = "v_x.d_dx";
  inline static term<P> const term0_dim0 = term<P>(term0_dim0_type, term0_dim0_func, term0_dim0_time_dependent, term0_dim0_flux, term0_dim0_data, term0_dim0_name, dim0);

  // term0 dim1
  static coefficient_type constexpr term0_dim1_type = coefficient_type::mass;
  inline static g_func_type<P> const term0_dim1_func = &g_func_identity;
  static bool constexpr term0_dim1_time_dependent = false;
  inline static fk::vector<P> const term0_dim1_data; // empty in this case
  static flux_type constexpr term0_dim1_flux = flux_type::central;
  static auto constexpr term0_dim1_name      = "massY";
  inline static term<P> const term0_dim1 = term<P>(term0_dim1_type, term0_dim1_func, term0_dim1_time_dependent, term0_dim1_flux, term0_dim1_data, term0_dim1_name, dim1);

  // term0 dim2
  static coefficient_type constexpr term0_dim2_type = coefficient_type::mass;
  inline static g_func_type<P> const term0_dim2_func = &g_func_identity;
  static bool constexpr term0_dim2_time_dependent = false;
  inline static fk::vector<P> const term0_dim2_data; // empty in this case
  static flux_type constexpr term0_dim2_flux = flux_type::central;
  static auto constexpr term0_dim2_name      = "massZ";
  inline static term<P> const term0_dim2 = term<P>(term0_dim2_type, term0_dim2_func, term0_dim2_time_dependent, term0_dim2_flux, term0_dim2_data, term0_dim2_name, dim2);

  // term0 (assemble)
  inline static const std::vector<term<P>> terms0 = {term0_dim0, term0_dim1,term0_dim2};

  // term1

  // term1 dim0
  static coefficient_type constexpr term1_dim0_type = coefficient_type::mass;
  inline static g_func_type<P> const term1_dim0_func = &g_func_identity;
  static bool constexpr term1_dim0_time_dependent = false;
  inline static fk::vector<P> const term1_dim0_data; // empty in this case
  static flux_type constexpr term1_dim0_flux = flux_type::central;
  static auto constexpr term1_dim0_name      = "massX";
  inline static term<P> const term1_dim0 = term<P>(term1_dim0_type, term1_dim0_func, term1_dim0_time_dependent, term1_dim0_flux, term1_dim0_data, term1_dim0_name, dim0);

  // term1 dim1
  static coefficient_type constexpr term1_dim1_type = coefficient_type::grad;
  inline static g_func_type<P> const term1_dim1_func = &g_func_identity;
  static bool constexpr term1_dim1_time_dependent = false;
  inline static fk::vector<P> const term1_dim1_data; // empty in this case
  static flux_type constexpr term1_dim1_flux = flux_type::central;
  static auto constexpr term1_dim1_name      = "v_y.d_dy";
  inline static term<P> const term1_dim1 = term<P>(term1_dim1_type, term1_dim1_func, term1_dim1_time_dependent, term1_dim1_flux, term1_dim1_data, term1_dim1_name, dim1);

  // term1 dim2
  static coefficient_type constexpr term1_dim2_type = coefficient_type::mass;
  inline static g_func_type<P> const term1_dim2_func = &g_func_identity;
  static bool constexpr term1_dim2_time_dependent = false;
  inline static fk::vector<P> const term1_dim2_data; // empty in this case
  static flux_type constexpr term1_dim2_flux = flux_type::central;
  static auto constexpr term1_dim2_name      = "massZ";
  inline static term<P> const term1_dim2 = term<P>(term1_dim2_type, term1_dim2_func, term1_dim2_time_dependent, term1_dim2_flux, term1_dim2_data, term1_dim2_name, dim2);

  // term1 (assemble)
  inline static const std::vector<term<P>> terms1 = {term0_dim0, term0_dim1,term0_dim2};

  
  // term2
  
  // term2 dim0
  static coefficient_type constexpr term2_dim0_type = coefficient_type::mass;
  inline static g_func_type<P> const term2_dim0_func = &g_func_identity;
  static bool constexpr term2_dim0_time_dependent = false;
  inline static fk::vector<P> const term2_dim0_data; // empty in this case
  static flux_type constexpr term2_dim0_flux = flux_type::central;
  static auto constexpr term2_dim0_name      = "massX";
  inline static term<P> const term2_dim0 = term<P>(term2_dim0_type, term2_dim0_func, term2_dim0_time_dependent, term2_dim0_flux, term2_dim0_data, term2_dim0_name, dim0);

  // term2 dim1
  static coefficient_type constexpr term2_dim1_type = coefficient_type::mass;
  inline static g_func_type<P> const term2_dim1_func = &g_func_identity;
  static bool constexpr term2_dim1_time_dependent = false;
  inline static fk::vector<P> const term2_dim1_data; // empty in this case
  static flux_type constexpr term2_dim1_flux = flux_type::central;
  static auto constexpr term2_dim1_name      = "massY";
  inline static term<P> const term2_dim1 = term<P>(term2_dim1_type, term2_dim1_func, term2_dim1_time_dependent, term2_dim1_flux, term2_dim1_data, term2_dim1_name, dim1);

  // term2 dim2
  static coefficient_type constexpr term2_dim2_type = coefficient_type::grad;
  inline static g_func_type<P> const term2_dim2_func = &g_func_identity;
  static bool constexpr term2_dim2_time_dependent = false;
  inline static fk::vector<P> const term2_dim2_data; // empty in this case
  static flux_type constexpr term2_dim2_flux = flux_type::central;
  static auto constexpr term2_dim2_name      = "v_z.d_dz";
  inline static term<P> const term2_dim2 = term<P>(term2_dim2_type, term2_dim2_func, term2_dim2_time_dependent, term2_dim2_flux, term2_dim2_data, term2_dim2_name, dim2);

  // term2 (assemble)
  inline static const std::vector<term<P>> terms2 = {term2_dim0, term2_dim1, term2_dim2};

  // assemble terms
  inline static term_set<P> const terms = {terms0, terms1, terms2};

Edited 3 months ago by Graham Lopez
Related issues
0

Related merge requests
1

    Feature/coefficients
    asgard/asgard !41

Graham Lopez
Graham Lopez @bgl · 3 months ago
Owner

    yes, there are some long lines (although see next point), but readabiliy may trump lone lines?

Keep in mind that for a lot of people, readability is reduced by longer lines. For example, in your proposed format, I now have to scroll my browser side to side, and my browser is using half of a 4K monitor. This is much much worse when using a normally-sized terminal or IDE pane for developing the code.

Also, why would I want to see all of the elements of a list on the same line? If anything, I would want to go the other way and turn off formatting and force them to be one per line, as we tend to naturally write down lists of things.

Automatic code formatting is never perfect for everyone in every case, but it is easy and consistent which is the overall long-term win. It can always be spot-tuned, but this should be used sparingly because it adds maintenance.

    and then also, do we have to use the &PDE_continuity_3:: qualifier?

Technically, no, I don't think we do. @3bm might have had a reason to prefer this. Barring further reasoning, I am fine to remove it.

    and perhaps another suggestion, ... can we clump the construction of dimensions, terms, and sources seperately as in the matlab

Of course. There always seem to be at least two axes along which things can be organized, and we often go back on forth on which way is better.

Thank you for the suggestions!
Green, David L
Green, David L @dg6 · 3 months ago
Owner

I think my main objective here is to try and make the PDE files be "organized" in the sense of being quickly able to see, here is the section where my terms are, here are my dimensions, etc. As the number of lines goes up, that part gets harder to see. Yes, you can see more of the details of each section, but the ability to see that there are sections goes away (as it spans more than the vertical space you have to work with - certainly this will be the case for higher D and more terms). Of course, this is subjective, and we will see how it works as we go along.
McDaniel, Benjamin T
McDaniel, Benjamin T @3bm · 3 months ago
Developer

    and then also, do we have to use the &PDE_continuity_3:: qualifier?

if I recall correctly, we do have to use the class name there to get the static function handle, but I am fine to remove it if I'm wrong.

    and perhaps another suggestion, ... can we clump the construction of dimensions, terms, and sources seperately as in the matlab

the organization is also a concern for me. it takes an unfortunate amount of text to get these objects configured, but for most of it we can reorganize with no functional difference. I will take another look at how it's done in the matlab and mimic that ordering if you think it's clearer.
Graham Lopez
Graham Lopez @bgl · 3 months ago
Owner

    I think my main objective here is to try and make the PDE files be "organized" in the sense of being quickly able to see, here is the section where my terms are, here are my dimensions, etc.

Yep, and it makes sense. If it sounded like I was opposed, that is not actually the case. Just that we struggle with understandability issues, and admittedly only get it right (optimistically) 50% of the time (when there are 2 choices).

As @3bm said, for now we're just trying to get it all down. Once we see can see everything together, then we will work more on laying it out (and we'll start with your suggestions).
McDaniel, Benjamin T
McDaniel, Benjamin T @3bm · 3 months ago
Developer

take a look what's in develop now:https://code.ornl.gov/asgard/asgard/tree/develop/src/pde and let me know if this improves the readability.

I was wrong; the namespace qualifiers aren't necessary, provided that the functions are defined in the file before they are referenced.
Edited by McDaniel, Benjamin T 3 months ago
Graham Lopez
Graham Lopez @bgl · 3 months ago
Owner

Other codes with ideas?

    Moose https://moose.inl.gov/SitePages/Home.aspx
    mfem https://github.com/mfem/mfem
    Gkyl http://www.ammar-hakim.org/
    bout++ https://github.com/boutproject/BOUT-dev

Edited by Graham Lopez 3 months ago
Graham Lopez @bgl changed title from perhaps use more clang format off within the PDE spec for more human readability? to ideas to improve PDE spec understandability 3 months ago
Graham Lopez @bgl mentioned in merge request !41 (merged) 3 months ago
Graham Lopez
Graham Lopez @bgl · 3 months ago
Owner

another (simple) idea: split up declarations/defintions
Graham Lopez @bgl assigned to @dg6 and @bgl 1 month ago

**Comment by mkstoyanov** [comment]
Stale issue, open a new one, if still relevant. (good idea though)
