### ISSUE TITLE
Fix matlab plotting for non-uniform levels

### ISSUE THREAD

**Issue by ckendrick** [project-asgard/asgard#420]
Running with a non-uniform level such as `./asgard -l "2 3"` when compiled with `-DASGARD_USE_MATLAB=ON` causes an error when trying to plot the solution in Matlab:

```
Index in position 1 exceeds array bounds (must not exceed 8).

Error in plot_fval (line 46)
    f_slice = f_nD(sy,:);

terminate called after throwing an instance of 'matlab::execution::MATLABExecutionException'
  what():  Index in position 1 exceeds array bounds (must not exceed 8).
Aborted
```

This is likely caused by a col/row major conversion issue between C++ and Matlab, though plots still seem to be correct for uniform levels. [Passing `f_val` to Matlab](https://github.com/project-asgard/asgard/blob/97eb56d9f0d0bafcf3ba9e601724c4c1962716ec/src/matlab_plot.cpp#L327) should ensure correct layout. Newer versions of Matlab allow for a memory layout option when using the data engine array factory.

**Comment by mkstoyanov** [comment]
Moving over to general PDE reconstruction through Python or Python + MATLAB. This circumvents the limitations of the old real space MATLAB plotting approach.
