### ISSUE TITLE
legendre weights function fixes for correctness/clarity

### ISSUE THREAD

**Issue by grahamlopez** [project-asgard/asgard#43]
ASGarD
    asgardasgard
    Issues
    #43

Open
Opened 3 months ago by McDaniel, Benjamin T
Close issue
New issue
legendre weights function fixes for correctness/clarity

after discussion w/ @tqd:

    update variable names per discussion: y->initial guesses, etc.
    make fixes on https://code.ornl.gov/asgard/asgard/blob/develop/src/quadrature.cpp#L239 (remove trailing+1), https://code.ornl.gov/asgard/asgard/blob/develop/src/quadrature.cpp#L270 (remove)
    bring up updated matlab script and regenerate test values

Related issues
0

McDaniel, Benjamin T
McDaniel, Benjamin T @3bm · 3 months ago
Developer

also, while I'm there, clean it up.
Younkin, Timothy R
Younkin, Timothy R @tqd · 3 months ago
Developer

Updated lgwt.m routine has been pushed to matlab reference branch
Graham Lopez @bgl added help_wanted label 3 months ago

**Comment by bmcdanie** [comment]
closed by #115 - don't know why the issue was not closed.
