### ISSUE TITLE
coefficient testing - increase coverage

### ISSUE THREAD

**Issue by grahamlopez** [project-asgard/asgard#44]
ASGarD
    asgardasgard
    Issues
    #44

Open
Opened 3 months ago by McDaniel, Benjamin T
Close issue
New issue
coefficient testing - increase coverage

currently, the coefficients component testing only covers cases that are used by the pdes we have implemented - continuity1, 2, 3.

these pdes do not have time dependent terms, or terms with stiffness operators, so the corresponding branches of the coefficient generation routine are not under test.

mock up a pde with stiffness terms/time dependent gfuncs and test.
Related issues
0

Related merge requests
1

    Feature/coefficients
    asgard/asgard !41
Graham Lopez @bgl added help_wanted label 3 months ago
McDaniel, Benjamin T @3bm mentioned in merge request !41 (merged) 3 months ago
Graham Lopez
Graham Lopez @bgl · 3 months ago
Owner

we should really be testing all of the individual functions in the "coefficients" component
Graham Lopez @bgl assigned to @hl8 1 month ago
Green, David L
Green, David L @dg6 · 1 week ago
Owner

The stiffness operator will get rewritten anyway. It already has been in the matlab.

The time dependent terms etc, yes. The next set of PDEs in the matlab should cover most of these.

**Comment by grahamlopez** [comment]
@dlg0 you've recently been thinking about coefficients and testing, both. Do you have any insights on this issue? Does it depend on a PDE re-work?

**Comment by dlg0** [comment]
In my latest round of PR's, I've added coverage for the `diff` operator type, which replaces the `stiff` type - so that handles that aspect of this issue. The time-dependent aspec is mostly moot since it will call the same routines, just inside the time loop.

**Comment by dlg0** [comment]
I expect we can close this after merging the diffusion PR.
