### ISSUE TITLE
Add documentation for how to register a new PDE

### ISSUE THREAD

**Issue by ckendrick** [project-asgard/asgard#457]
**Is your feature request related to a problem? Please describe.**
There is currently not a way to automatically register a new PDE with ASGarD. Until #453 is implemented, there should be documentation for where and how to add a new PDE class.

**Describe the solution you'd like**
A small section should be added to the Wiki/docs describing necessary changes to include a new PDE. The PDE added in #456 could also be referenced as an example.

**Describe alternatives you've considered**
N/A

**Additional context**
It is currently unclear for new users how to add custom PDEs to the code.

**Comment by mkstoyanov** [comment]
An easy fix here is to take #456 and make it into a doxygen example. Basically, add the code to the web-page together with some comments. then we can work on #453

**Comment by mkstoyanov** [comment]
We'll be moving to a new API, we can close this.
