### ISSUE TITLE
issues finding mkl_cblas.h

### ISSUE THREAD

**Issue by quantumsteve** [project-asgard/asgard#468]
**Describe the bug**

`ASGARD_MKL` is only defined if `BLA_VENDOR` is set into `Intel*`. It fails if `BLA_VENDOR=All`.  

I suspect we'd run into a similar issue with `ASGARD_OPENBLAS` but haven't tried to confirm.

On Ubuntu the `libmkl-dev` package has the cblas header in `/usr/include/mkl/mkl_cblas.h`. GCC finds `#include "mkl_cblas.h"` without issues but clang needs `#include "mkl/mkl_cblas.h"`. The later also works with GCC.

I tried updating our Docker container to use oneAPI MKL. `source /opt/intel/oneapi/setvars.sh` does set `CPATH=/opt/intel/oneapi/mkl/2022.2.1/include` and therefore requires `#include "mkl_cblas.h"` 

 **To Reproduce**
1. git commit hash being built
2. cmake command
3. full program/test invocation command
4. additional steps 

**Expected behavior**

1. Use MKL without setting BLA_VENDOR by hand.
2. Successfully find and include mkl_cblas.h

**System:**
 - system name [e.g. fusiont5, summit]
 - modules loaded [e.g. output of `module list`]
 - other systems where this is reproducible [e.g. "my laptop", "none"]

Ubuntu 20.04, Ubuntu 22.04 Docker container

**Additional context**

I suspect we need something similar to QMCPACK.
https://github.com/QMCPACK/qmcpack/blob/687b3db43c1fadd063c0d461995d777c5b49809b/CMake/FindMKL.cmake#L7

**Comment by quantumsteve** [comment]
Alternatively, switch to Intel's CMake config for MKL.

https://www.intel.com/content/www/us/en/develop/documentation/onemkl-macos-developer-guide/top/getting-started/cmake-config-for-onemkl.html

**Comment by mkstoyanov** [comment]
stale, doesn't seem to be an issue anymore, OneMKL works in CI
