### ISSUE TITLE
Coefficients - clarifying comments on function inputs/outputs

### ISSUE THREAD

**Issue by grahamlopez** [project-asgard/asgard#49]
ASGarD
    asgardasgard
    Issues
    #49

Open
Opened 3 months ago by McDaniel, Benjamin T
Close issue
New issue
Coefficients - clarifying comments on function inputs/outputs

@tqd can you help us look at coefficients.cpp? I broke the coefficient generation routine into some smaller parts to clarify a little, but we need to comment the functions w/ basic desc. of inputs/outputs
Related issues
0

Related merge requests
1

    Feature/coefficients
    asgard/asgard !41

    McDaniel, Benjamin T @3bm mentioned in merge request !41 (merged) 3 months ago
    Graham Lopez @bgl assigned to @tqd 1 month ago

**Comment by bmcdanie** [comment]
@dlg0 re implemented this and took out my poor attempts at extracting/naming the pieces - this issue is obselete.
