### ISSUE TITLE
Speeding up generate_all_coefficients

### ISSUE THREAD

**Issue by stefan-schnake** [project-asgard/asgard#493]
[`generate_all_coefficients`](https://github.com/project-asgard/asgard/blob/develop/src/coefficients.cpp#L18) is called several times in IMEX and is the slowest part of the code (per @ckendrick).  This is probably due to the LHS mass matrix is being generated from scratch every time `generate_all_coefficients` is called [link](https://github.com/project-asgard/asgard/blob/develop/src/coefficients.cpp#L36-L45).  This LHS matrix is often the identity matrix, but it's stored as a dense matrix, and then is inverted and left multiplied to the 1D stiffness matrices (thus a dgemm is called).

This should be an easy fix by checking the `g_func_in' and `dv_func_in' inputs against `null_gfunc' and not computing the matrix if so.  

Assigning @quantumsteve.

**Comment by quantumsteve** [comment]
I'm running into issues comparing `g_func_type = std::function<P(P const, P const)>`, as operator== only works against nullptr.

https://stackoverflow.com/questions/20833453/comparing-stdfunctions-for-equality

Where is a similar comparison being done in ASGarD?

**Comment by mkstoyanov** [comment]
We cannot compare like that, there is no C++ way to compare if a function is just `return 1.0;`. The `==` operator works on the level of memory (i.e., the address of the function) and the alternative is to check if the method returns `1.0` at each quadrature point, which is too much.

The correct way to do this is to add a flag to the dimension/term class, which will indicate whether the function is identity or not. We can also have an overloaded constructor, if we don't provide a `g_func_in` then the code will assume we are working with identity.

**Comment by quantumsteve** [comment]
I'm leaning towards making the default parameter for `jacobian` and `lhs_mass_func` to be `nullptr`. The getters would have the logic to either return the stored function or `null_gfunc`. Checking for identity would be another function comparing against `nullptr`.

**Comment by mkstoyanov** [comment]
The only problem that I foresee with this is that we would like to be able to accept lambdas, `std::functional` or pointers to static functions.

Particularly the lambda feature is important to allow capture of extra data that the user may need. I really want to move away from the use of `static` variables in the PDE classes.

**Comment by quantumsteve** [comment]
To clarify, the function signatures won't change, just the default argument. std::function has [operator bool](https://en.cppreference.com/w/cpp/utility/functional/function/operator_bool) so wrapping in something like std::optional is unnecessary.
