### ISSUE TITLE
Update continuity 1d documentation

### ISSUE THREAD

**Issue by quantumsteve** [project-asgard/asgard#498]
**Describe the bug**

[The continuity_1 PDE](https://github.com/project-asgard/asgard/blob/e8327e31291527af8a990b0d9f88c5608119db27/src/pde/pde_continuity1.hpp#L21) contains 2 source terms that are not included in the documentation.

Please update the  documentation to match the code.

**Comment by quantumsteve** [comment]
@stefan-schnake

**Comment by mkstoyanov** [comment]
We fixed this as part of the JOSS submission, right?

**Comment by quantumsteve** [comment]
yes

**Comment by quantumsteve** [comment]
https://github.com/project-asgard/asgard/pull/665
