### ISSUE TITLE
Improvements to examples page

### ISSUE THREAD

**Issue by quantumsteve** [project-asgard/asgard#501]
This might be better done in a different PR, but I think it would be good to update the example page to mention that the red curves are the analytical solution since we don't explicitly say that. Also, updating the 2D plot with your changes to include slice coordinates might be helpful.

_Originally posted by @ckendrick in https://github.com/project-asgard/asgard/pull/500#pullrequestreview-1295899358_

**Comment by mkstoyanov** [comment]
no longer relevant
