### ISSUE TITLE
Cannot upgrade CUDA version on AWS CodeBuild 

### ISSUE THREAD

**Issue by quantumsteve** [project-asgard/asgard#508]
**Describe the bug**

**To Reproduce**

Change `FROM nvidia/cuda:11.4.3-devel-ubuntu20.04` to `FROM nvidia/cuda:11.5.2-devel-ubuntu20.04`
https://github.com/project-asgard/containers/blob/main/gpu/Dockerfile#L1

```
PROVISIONING | Fault | Internal Service Error: CodeBuild is experiencing issues
```

**Expected behavior**

I'd like to move to a newer CUDA version, ideally 12.1

**System:**
 - system name [e.g. fusiont5, summit]
    AWS codeBuild
 - modules loaded [e.g. output of `module list`]
 - other systems where this is reproducible [e.g. "my laptop", "none"]

**Additional context**

**Comment by mkstoyanov** [comment]
CUDA 12 is too aggressive as a requirement, it is still not the default on many systems and there are API changes to some of the libraries (I'm worried about conflicts in kronmult). I would rather figure out the internal build error and stay to 11 for a while longer.

Looking at the build, we seem to be using a single Dockerfile and installing ROCm to that. ROCm and OneAPI have their own containers now. We should be using different containers, i.e., vanilla Ubuntu for CPU-only testing and the corresponding vendor container for the GPU types. That will reduce the potential for problems and may even fix this one.

**Comment by quantumsteve** [comment]
I was hoping to get up to the [11.7.1-devel-ubuntu22.04](https://hub.docker.com/layers/nvidia/cuda/11.7.1-devel-ubuntu22.04/images/sha256-5f711addc3f20a0a2120738be907a38d80a38d8fb567c8cfaa72af8719254570?context=explore) base image so all VMs are using Ubuntu 22.04.

CodeBuild only provides NVIDIA GPUs, which @ckendrick worked around by installing HIP from source. If we add ROCm/HIP, we may be better off using `fusionmi50` or similar as a dedicated CI machine.

**Comment by mkstoyanov** [comment]
I fully support bumping to ubuntu 22.04, but with 11.7.1 as opposed to 12.1

Do we have a HIP backend at the moment and I don't think it is of even moderate priority.

**Comment by quantumsteve** [comment]
We currently have 4 containers (clang-format, cpu, cpu-mkl, and gpu).

Correct, no work is currently being done to support AMD or Intel GPUs.

**Comment by mkstoyanov** [comment]
The excessive number of subfolders threw me off, I see the four containers now.

However, my point remains that the CUDA container also install ROCm, which is not needed, waste of time, and a potential source of conflicts and errors.

**Comment by mkstoyanov** [comment]
@quantumsteve is this still and issue? Are we working on it, or can we just close it.

**Comment by quantumsteve** [comment]
I tried again and successfully used an CUDA 11.8 Docker container on AWS CodeBuild. Not sure what's changed :man_shrugging:

**Comment by mkstoyanov** [comment]
The problem was either a side-effect of a bug or other refactored code, or the issue was on the AWS side.
