### ISSUE TITLE
Restart/Checkpoint Implementation

### ISSUE THREAD

**Issue by stefan-schnake** [project-asgard/asgard#514]
Add a flag to recover the current state/time from asgard_wavelet_X.h5 and run the simulation from there.  The things needed to be loaded are:
- hash_table (saved)
- wavespace data (saved)
- max_level (saved)
- current levels (saved)
- current time (saved)
- timestep (NOT saved)

We should use the adaptivity flag from the command line to determine whether we should adapt.  If adaptivity is not enabled, then the provided hash_table gives the constant grid that will not change.

**Comment by mkstoyanov** [comment]
@ckendrick How far along are we on this one? Can we close it?

**Comment by ckendrick** [comment]
It is done in a branch but a PR has not been made yet. Waiting on finishing the dependent PR beforehand.

**Comment by ckendrick** [comment]
Closed by #597 and #601.
