### ISSUE TITLE
Fix GPU adaptivity on IMEX solve

### ISSUE THREAD

**Issue by stefan-schnake** [project-asgard/asgard#516]
**Describe the bug**
GPU is not advancing in time when adaptivity and IMEX are enabled.  This could be an issue with the coefficient matrix change implemented that does not compute the 1D coefficient matrix at every timestep.

**Comment by mkstoyanov** [comment]
@ckendrick @stefan-schnake Can we verify is this is still an issue with the current kronmult implementation (i.e., the one in #541)

**Comment by ckendrick** [comment]
I believe this should be fixed in #525 and should be independent of changes in kronmult. This also could have been happening from the overallocation issue that was fixed in #527.

**Comment by mkstoyanov** [comment]
Then we can close it. We should be more proactive in closing these issues.

**Comment by ckendrick** [comment]
I didn't close this yet since #525 is not yet merged in.
