### ISSUE TITLE
Make coefficient generation level dependent

### ISSUE THREAD

**Issue by stefan-schnake** [project-asgard/asgard#518]
Currently, when coefficients are to be built, the coefficients for each level are built regardless if they will be used this timestep.  This is because the majority of the earlier PDEs are time independent in their coefficients so precomputing make sense.  

The fix is to rewrite the coefficient generation to take in a level vector as input, then build all coefficients at the specified level for each dimension.  Then, at the prep step before timestepping, we can generate all coefficients for each level for the PDEs that have  time-independent coefficients while speeding up problems with time-dependent coefficients.

**Comment by mkstoyanov** [comment]
This has to be combined with storing the coefficients in a sparse structure. I'll probably tackle that right after the sparse matrix PR.

**Comment by mkstoyanov** [comment]
Cole did that a while back.
