### ISSUE TITLE
Multi-wavelet transform operation optimization for speed and storage

### ISSUE THREAD

**Issue by grahamlopez** [project-asgard/asgard#52]
ASGarD
    asgardasgard
    Issues
    #52

Open
Opened 2 months ago by Younkin, Timothy R
Close issue
New issue
Multi-wavelet transform operation optimization for speed and storage

The multi-wavelet transform matrix has a particular sparsity structure as well as using repeated coefficients (and known factors of those coefficients) throughout. Therefore the storage of this matrix and its application to transform to the multi-resolution basis can be optimized.

via @e6d on Slack (March 21, 2019):

Taking advantage of the special sparsity structure in FMWT may be a savings in flops of a factor of order 2^L/(L+1) , where L is number of levels. For L is about 10, then ratio of 2^10 over 11 is about a factor of 90X in work. Note the storage is O( kLn) (storing just the unique blocks) instead of O(n*n) (FMWT as full matrix), n = k * 2^L. So again a savings in storage of ratio that is O( 2^L / (L+1) ). So for degree k = 10, levels L = 12, it will be difference about 13 GBytes vs 40 MBytes.

An operation to optimize this has been coded in the matlab reference branch here
Related issues
0

Related merge requests
2

    WIP: Resolve "Multi-wavelet transform operation optimization for speed and storage"
    asgard/asgard !57
    Optimized Application of FMWT
    asgard/asgard !58

When these merge requests are accepted, this issue will be closed automatically.

    Younkin, Timothy R @tqd added feature label 2 months ago
    Younkin, Timothy R @tqd created merge request !57 (closed) to address this issue 1 month ago
    Younkin, Timothy R @tqd mentioned in merge request !57 (closed) 1 month ago
    Graham Lopez @bgl added performance label 1 month ago
    Graham Lopez @bgl mentioned in merge request !58 1 month ago
    Graham Lopez
Graham Lopez @bgl · 2 weeks ago
Owner

related to #67 ?
Graham Lopez @bgl mentioned in issue #67 2 weeks ago

**Comment by bmcdanie** [comment]
@tyounkin is this completed with #104 ?

**Comment by tyounkin** [comment]
@bmcdanie yes it is
