### ISSUE TITLE
Change default parameter initializations

### ISSUE THREAD

**Issue by ckendrick** [project-asgard/asgard#520]
`parameter` initialization functions should be changed to use a lambda where appropriate.

An example PDE that registers `parameter`s:
https://github.com/project-asgard/asgard/blob/01016aa01129e560a14093b557e2b7f2c4c17ab0/src/pde/pde_two_stream.hpp#L23-L28

An example corresponding `parameter` function that can be replaced with a lambda for initialization:
https://github.com/project-asgard/asgard/blob/01016aa01129e560a14093b557e2b7f2c4c17ab0/src/pde/pde_two_stream.hpp#L150-L155

**Comment by mkstoyanov** [comment]
Initialization revamped in #716 and the prams/moments will come next.
