### ISSUE TITLE
Add ability to skip performance timers

### ISSUE THREAD

**Issue by ckendrick** [project-asgard/asgard#521]
There should be compile time option added to disable `tools::timer.start()` and `tools::timer.stop()` with a noop.
This can probably be done similarly to how `expect` is implemented:
https://github.com/project-asgard/asgard/blob/01016aa01129e560a14093b557e2b7f2c4c17ab0/src/tools.hpp#L15-L19

**Comment by mkstoyanov** [comment]
I agree but this should be done with another option and not the `NDEBUG`, i.e., `-DASGARD_USE_TIMER=ON/OFF` where the default is `ON`.

The time does not take much and sometimes we want it in `Release` mode too, but not always.

This should be easy with just replacing the existing methods with no-op and returning empty strings.
