### ISSUE TITLE
Kronmult ~7.5x slower with clang 14 vs gcc 11

### ISSUE THREAD

**Issue by quantumsteve** [project-asgard/asgard#540]
**Describe the bug**
GCC 11.3.0
```
svh@PC102795:~/Documents/asgard/build$ OMP_PROC_BIND=close OMP_NUM_THREADS=20 ./asgard-kronmult-benchmark 2 4 4096 12288 1000
benchmarking:
dimensions: 2  n: 4  num_y: 4096  operator_size: 12288  num_matrices: 1000
benchmark setup time: 6.533 seconds.
single precision: 182.8424 Gflops / second.
double precision: 156.1806 Gflops / second.
svh@PC102795:~/Documents/asgard/build$ OMP_PROC_BIND=close OMP_NUM_THREADS=10 ./asgard-kronmult-benchmark 2 4 4096 12288 1000
benchmarking:
dimensions: 2  n: 4  num_y: 4096  operator_size: 12288  num_matrices: 1000
benchmark setup time: 6.548 seconds.
single precision: 101.7122 Gflops / second.
double precision: 83.2466 Gflops / second.
svh@PC102795:~/Documents/asgard/build$ OMP_PROC_BIND=close OMP_NUM_THREADS=5 ./asgard-kronmult-benchmark 2 4 4096 12288 1000
benchmarking:
dimensions: 2  n: 4  num_y: 4096  operator_size: 12288  num_matrices: 1000
benchmark setup time: 6.534 seconds.
single precision: 54.3392 Gflops / second.
double precision: 44.9719 Gflops / second.
```
clang 14.0.0
```
svh@PC102795:~/Documents/asgard/build$ OMP_PROC_BIND=close OMP_NUM_THREADS=20 ./asgard-kronmult-benchmark 2 4 4096 12288 1000
benchmarking:
dimensions: 2  n: 4  num_y: 4096  operator_size: 12288  num_matrices: 1000
benchmark setup time: 29.44 seconds.
single precision: 19.8238 Gflops / second.
double precision: 19.0290 Gflops / second.
svh@PC102795:~/Documents/asgard/build$ OMP_PROC_BIND=close OMP_NUM_THREADS=10 ./asgard-kronmult-benchmark 2 4 4096 12288 1000
benchmarking:
dimensions: 2  n: 4  num_y: 4096  operator_size: 12288  num_matrices: 1000
benchmark setup time: 29.502 seconds.
single precision: 10.0840 Gflops / second.
double precision: 9.9676 Gflops / second.
svh@PC102795:~/Documents/asgard/build$ OMP_PROC_BIND=close OMP_NUM_THREADS=5 ./asgard-kronmult-benchmark 2 4 4096 12288 1000
benchmarking:
dimensions: 2  n: 4  num_y: 4096  operator_size: 12288  num_matrices: 1000
benchmark setup time: 29.492 seconds.
single precision: 5.5760 Gflops / second.
double precision: 5.4787 Gflops / second.
```
**To Reproduce**
1. git commit hash being built
`5a1e28943391f1b828f78663440f39064aaff76f`
2. cmake command
`cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DASGARD_RECOMMENDED_DEFAULTS=ON ../`
3. full program/test invocation command
`OMP_PROC_BIND=close OMP_NUM_THREADS=20 ./asgard-kronmult-benchmark 2 4 4096 12288 1000`
4. additional steps 
**Expected behavior**

**System:**
 - system name [e.g. fusiont5, summit]
 office workstation, ubuntu 22.04
 - modules loaded [e.g. output of `module list`]
  - other systems where this is reproducible [e.g. "my laptop", "none"]
 Similar issues on my laptop with an Ubuntu 23.04 container (gcc 12, clang 16)

**Additional context**

**Comment by mkstoyanov** [comment]
Can you verify that OpenMP is enabled?

If the recommended defaults fail to find OpenMP, then it is disabled automatically.

PS: To use clang + OpenMP on Ubuntu, you need to get "libiomp"installed.

**Comment by quantumsteve** [comment]
```
svh@PC102795:~/Documents/asgard/build$ CXX=clang++-14 cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DASGARD_RECOMMENDED_DEFAULTS=ON ..
-- The CXX compiler identification is Clang 14.0.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++-14 - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.34.1") 
-- Registering project Catch2
-- CMAKE_BUILD_TYPE is Release
-- Looking for sgemm_
-- Looking for sgemm_ - not found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Looking for sgemm_
-- Looking for sgemm_ - found
-- Found BLAS: /opt/intel/oneapi/mkl/2023.1.0/lib/intel64/libmkl_intel_lp64.so;/opt/intel/oneapi/mkl/2023.1.0/lib/intel64/libmkl_intel_thread.so;/opt/intel/oneapi/mkl/2023.1.0/lib/intel64/libmkl_core.so;/usr/lib/x86_64-linux-gnu/libiomp5.so;-lm;-ldl  
-- Looking for cheev_
-- Looking for cheev_ - found
-- Found LAPACK: /opt/intel/oneapi/mkl/2023.1.0/lib/intel64/libmkl_intel_lp64.so;/opt/intel/oneapi/mkl/2023.1.0/lib/intel64/libmkl_intel_thread.so;/opt/intel/oneapi/mkl/2023.1.0/lib/intel64/libmkl_core.so;/usr/lib/x86_64-linux-gnu/libiomp5.so;-lm;-ldl;-lm;-ldl  
-- Found LINALG: TRUE  
-- Found OpenMP_CXX: -fopenmp=libomp (found version "5.0") 
-- Found OpenMP: TRUE (found version "5.0")  
-- Configuring done (6.1s)
-- Generating done (0.1s)
-- Build files have been written to: /home/svh/Documents/asgard/build
```

**Comment by quantumsteve** [comment]
@mkstoyanov Yes, CMake confirms that OpenMP is enabled and changing `OMP_NUM_THREADS` shows the number of GFLOPS scaling with the number of cores.

I'm guessing LLVM is treating `pragma #omp simd` differently.

**Comment by mkstoyanov** [comment]
Yes, this is real. I don't know what's wrong with clang.

If you want, you can comment out all the `omp simd` directives and check ... this can be a lot of work.

gcc and clang are on par when disabling `-march` and OpenMP.

**Comment by mkstoyanov** [comment]
https://clang.llvm.org/docs/OpenMPSupport.html


> #pragma omp declare simd: Partial. We support parsing/semantic analysis + generation of special attributes for X86 target, but still missing the LLVM pass for vectorization.


They are probably preventing LLVM from doing any vectorization at all.

We can look for a work-around, but do not change the code right now. I have done lots of changes to the kronmult as I am switching from pointers to arrays and indexing, better alignment and removing the excessive kronmult setup. Any workaround here will have to wait.

**Comment by mkstoyanov** [comment]
Can we have the `#pragma simd` statements in macros that are disabled for clang?

**Comment by quantumsteve** [comment]
> Can we have the `#pragma simd` statements in macros that are disabled for clang?

What is the rationale?

**Comment by mkstoyanov** [comment]
The 7.5x difference cannot be explained by missing AVX instructions. Clang has only partial understanding of `#pragma simd`, some per-processing is done but it is not vectorized in the end, which I interpret as if even the regular non-OpenMP vectorization isn't performed.

If we remove the `#pragma simd` statements, then some vectorization will still take place and clang will be faster. Still slower in the end by maybe 2x-3x, not all the way to 7.5x.

One quick test is to remove the `#pragma simd` statements and see how much faster clang gets. Maybe I'm wrong, but if clang gets significantly faster than it will be beneficial to remove the simd pragmas in the clang case.

**Comment by quantumsteve** [comment]
A macro like you describe above looks like the best option.
