### ISSUE TITLE
moving semantics for owning tensors

### ISSUE THREAD

**Issue by grahamlopez** [project-asgard/asgard#55]
ASGarD
    asgardasgard
    Issues
    #55

Open
Opened 2 months ago by Graham Lopez
Close issue
New issue
moving semantics for owning tensors

how to handle moves of owners? it messes with the lifetime ordering

we think this won't happen naturally (i.e. without explicitly calling std::move()), so we're going to say that views are invalidated when their owner is moved and wait to see if it bites anybody
Related issues
0

Graham Lopez @bgl added bug label 2 months ago

**Comment by bmcdanie** [comment]
we have not had an issue with this; there are checks in the owner that disallow these in the case of outstanding views.
