### ISSUE TITLE
Timer raises error on line 36  in tools.hpp

### ISSUE THREAD

**Issue by mkstoyanov** [project-asgard/asgard#551]
The timer raises error on line 36 in `tools.hpp` complaining about multiple identifiers.

It is ultra annoying as it can kill a long run over nothing.

@quantumsteve can you please find the reason, are not using the STL map correctly or what?

**Comment by quantumsteve** [comment]
I'll look at it tomorrow.

**Comment by mkstoyanov** [comment]
You obviously don't have to drop everything to work on that, but bump it higher on the priority list.

One thing that I fear is that we may be off on the flop count due to a bug in the timer (probably not but we need to make sure).

**Comment by quantumsteve** [comment]
@ckendrick @mkstoyanov Which combination of command-line arguments causes the assertion to fail? I've encountered the same error before, but am now struggling to re-create it.

**Comment by mkstoyanov** [comment]
The error registers in the assertion at line 36 in `tools.hpp` and you need to enable the assertions. The really annoying part is that it appears at seemingly random. I had a timer begin/end in the current PR where I was measuring the time to build the sparse matrix. After all the other changes that I made, the bug is not there.

Try putting a few random timers here and there, if you cannot create the bug, then maybe it was a consequence of another bug and we should know that.

**Comment by mkstoyanov** [comment]
Putting this on the back-burner. Anyone sees the bug, report here.

(there is a good chance that the bug does not exist and it only manifests as an after-effect from another bug)

**Comment by mkstoyanov** [comment]
Haven't seen this in a long time, I don't think it's a bug but a symptom of a bug (stack-smashing).
