### ISSUE TITLE
Remove MAC-OSX + MPI tests from the CI

### ISSUE THREAD

**Issue by mkstoyanov** [project-asgard/asgard#556]
There are no clusters using OSX and MPI, if we can run on a single Mac node we are good on Mac.

Let's remove the ScaLAPACK and MPI test from the CI with Mac.

**Comment by cianciosa** [comment]
Right now the Mac runners aren't using parallel make. This was originally done so problems with compiling could be diagnosed easier. But if you change it from

`make VERBOSE=1`

to

`make -j3`

should have a significant impact on reducing the CI run time.

**Comment by mkstoyanov** [comment]
Well that's double-bad. We need to remove the MPI tests and add the `make -j` command.

**Comment by quantumsteve** [comment]
I believe @stefan-schnake, @ckendrick and possibly @endeve regularly build ASGarD on MacOS.

**Comment by mkstoyanov** [comment]
Leave Mac, I want to support Mac. I don't want to waste time with Mac + MPI, nobody is using Mac + MPI. 

We already support multi-threading and soon we'll support multiple GPUs and that's all the performance that you can hope to get out of a single Mac. Mac + MPI is pointless, there are no Mac clusters.

**Comment by quantumsteve** [comment]
I'll create a PR to remove the MacOS MPI builds.
