### ISSUE TITLE
Reversing coarsen and refinement in adaptivity.  

### ISSUE THREAD

**Issue by stefan-schnake** [project-asgard/asgard#573]
In a single timestep, the current code coarsens the solution and then repeatedly refines until the tolerance is met.  This means that the result of time_advance might have lots of wasted DOFs that were only used to check tolerances.   This clogs up the IO routines and file sizes in adaptivity runs. 

I suggest we swap the order of coarsen and refine.  That was outputted solutions are more manageable.  @mkstoyanov should lend his thoughts on this.

**Comment by mkstoyanov** [comment]
We had many discussions on this and I think we have a plan ... more sophisticated than a simple reverse.

Coarsen/refinement should not mess with the IO. If you want less IO for plotting, we can pre-process the data dump and remove entries below eye-ball tolerance.
