### ISSUE TITLE
0 term kronmult bug

### ISSUE THREAD

**Issue by stefan-schnake** [project-asgard/asgard#582]
**Describe the bug**
[The relaxation problem](https://github.com/ckendrick/asgard/blob/1x3v_develop/src/pde/pde_relaxation_1x2v.hpp) an implicit PDE only.  Running it with `--kron-mode sparse` and '-x' currently fails.  This is because there are no terms in the pde file for the explicit portion of IMEX and this causes a crash.

Trying with `--kron-mode dense` raises the exception [here](https://github.com/project-asgard/asgard/blob/796f9cf035dcffdbc0052f7b81c2503dbf804e7b/src/asgard_kronmult_matrix.cpp#L86-L87).  

**Expected behavior**
if there are no terms present, we want to pass back a vector of zeros.

**Comment by mkstoyanov** [comment]
@stefan-schnake is this still a problem?

**Comment by stefan-schnake** [comment]
Yes.  Relaxation pdes are currently set to have a dummy explicit term that evaluates to 0: https://github.com/project-asgard/asgard/blob/develop/src/pde/pde_relaxation_1x1v.hpp#L192-L222
