### ISSUE TITLE
Automatic checkpoint restart

### ISSUE THREAD

**Issue by ckendrick** [project-asgard/asgard#585]
**Is your feature request related to a problem? Please describe.**
When running larger simulations on cluster environments via batch slurm scripts, there are times when the simulation is still running but the job exceeded its time limit. Currently, this requires the user to manually add `--restart <filename>` where `<filename>` is the last time step the simulation ran to before the job timed out.

This requires constant user awareness of running jobs and manual intervention to restart these, instead of easily adding additional batch jobs that depend on the first.

**Describe the solution you'd like**
We should extend the existing `--restart <filename>` option such that if `<filename>` is omitted, it will automatically scan the current directory for the last wavelet file and use that as the `<filename>` to restart from.

This would allow an initial job to be submitted, then another job submitted afterwards (which depends on the first job), but with the `--restart` option added. This can be repeated as many times as necessary, but the simulation will always restart from the last successful time step.

**Comment by mkstoyanov** [comment]
What is the filename scheme here? Is it something like `<filename>_<time step>`

Perhaps we can add another option, auto-restart that will save in two files `<filename>_current` and `<filename>_last` (the two are needed in case the job terminates in the middle of file writing). That is easy to search without knowing the last time-step.

Basically, we have one option for saving files with the aim for restart and another for plotting.

**Comment by ckendrick** [comment]
Yes, `<filename>_<time step>.h5` is the current naming scheme where `<time step>` is in increments of the `--wave_freq` option (the default filename is currently `asgard_wavelet_<time step>.h5` but this can be changed in `main.cpp`).

Keeping a `<filename>_current` and `<filename>_last` would definitely work. My only concern is we probably want to use both options - the ability to restart while also saving all the data files for plotting as normal. Perhaps we could save the `current` and `last` indices to a specific text file and use that to load the corresponding data if that text file exists?

I like your idea of keeping track of the current and last files. It is better than having to scan the directory to determine those indices, especially if there are thousands of files.

**Comment by mkstoyanov** [comment]
We have checkpoint restart, perhaps we can make it more robust but the feature exists.
