### ISSUE TITLE
Change matrix view interface

### ISSUE THREAD

**Issue by grahamlopez** [project-asgard/asgard#63]
ASGarD
    asgardasgard
    Issues
    #63

Open
Opened 1 month ago by Elwasif, Wael
Close issue
New issue
Change matrix view interface

The current API

template<typename P, mem_type mem>
template<mem_type, typename>
fk::matrix<P, mem>::matrix(fk::matrix<P, mem_type::owner> const &owner,
                           int const start_row, int const stop_row,
                           int const start_col, int const stop_col)

Leads to a call that repeats the spec for the start corner as in

cfmwt.set_submatrix(cn / 2, 0,
      fk::matrix<R,mem_type::view>(fmwt, degree * max_level/2, degree * max_level/2 + cn/2 - 1, 0, cn-1));

Maybe a better API should mimic the existing extract_submatrix() API

template<typename P, mem_type mem>
fk::matrix<P>
fk::matrix<P, mem>::extract_submatrix(int const row_idx, int const col_idx,
                                      int const num_rows,
                                      int const num_cols)

So the call above would be

cfmwt.set_submatrix(cn / 2, 0,
fk::matrix<R,mem_type::view>(fmwt, degree * max_level/2, 0, cn/2, cn));

Related issues
0

Elwasif, Wael @elwasif added feature hygeine labels 1 month ago

**Comment by bmcdanie** [comment]
I think the goal here should be to unify the set/extract submatrix and view constructor apis WRT indexing.

**Comment by mkstoyanov** [comment]
Stale issue, open a new one, if still relevant.
