### ISSUE TITLE
GPU based Gmres with function handles

### ISSUE THREAD

**Issue by grahamlopez** [project-asgard/asgard#65]
ASGarD
    asgardasgard
    Issues
    #65

Open
Opened 1 month ago by Lu, Hao
Close issue
New issue
GPU based Gmres with function handles
Related issues
0

Lu, Hao
Lu, Hao @hl8 · 1 month ago
Developer

1. Paralution does not support function handles in their brief documentation. http://www.paralution.com/downloads/paralution-um.pdf -> emailing developer to see if they have more detailed documents

2. 
![image](https://user-images.githubusercontent.com/5647645/59166559-082a7200-8af9-11e9-9db2-36849569cbf6.png)
        gmres_pusedocode -> To be clear, the red circle part is where the function handle should take place, instead of explicit matrix A

3. Found an GPU (library https://github.com/sheldonucr/GPU-GMRES/tree/master/src) that we could go in and modified the part that matrix A is used. -> Understand the use of this GMRES and check with David to see if this is suitable
Edited by Lu, Hao 1 month ago
Lu, Hao @hl8 added help_wanted label 1 month ago

**Comment by haolu12** [comment]
#include "tensors.hpp"
#include <petscksp.h>
#include <petscmat.h>
#include <petscvec.h>
#include <stdlib.h> 

#define myInt long


PetscErrorCode MyKSPMonitor(KSP ksp,PetscInt n,PetscReal rnorm,void *dummy)
{
  PetscPrintf(PETSC_COMM_WORLD,"iteration %D KSP Residual norm %4.13e \n",n,rnorm);
  return 0;
}


int merge_petsc(Vec& pb, Vec& pu, Mat& A)
{
	Vec px, normV;
	MatMult(A,pu,pb);
	PetscErrorCode ierr;
	
	ierr = VecDuplicate(pu,&px);CHKERRQ(ierr);
	ierr = VecView(pb,PETSC_VIEWER_STDOUT_WORLD);CHKERRQ(ierr);


	
	// Setup Krov Space solver
	KSP ksp;         /* KSP context */
	PC pc;           /* PC context */
	PetscReal norm;  /* norm of solution error */
	PetscInt n =30;	
	//Create linear solver context
	ierr = KSPCreate(PETSC_COMM_WORLD,&ksp);CHKERRQ(ierr);
	// A as matrix and pre-conditioner
	ierr = KSPSetOperators(ksp,A,A);CHKERRQ(ierr);
	// Set up preconditioner
	//ierr = KSPGetPC(ksp,&pc);CHKERRQ(ierr);
	//ierr = PCSetType(pc,PCBJACOBI);CHKERRQ(ierr);
	//ierr = PCBJacobiSetTotalBlocks(pc,4,blks);CHKERRQ(ierr)
	//ierr = PCSetType(pc,PCJACOBI);CHKERRQ(ierr);
	
	// Set up tolerance and type of solver
	ierr = KSPSetTolerances(ksp,1.e-5,PETSC_DEFAULT,PETSC_DEFAULT,PETSC_DEFAULT);
	ierr = KSPSetType(ksp,KSPGMRES);CHKERRQ(ierr);
	ierr = KSPGMRESCGSRefinementType(KSP_GMRES_CGS_REFINE_ALWAYS);

	// Set up what do to for monitoring convergence
	ierr = KSPMonitorSet(ksp,MyKSPMonitor,NULL,0);CHKERRQ(ierr);

	// Solve
	PetscPrintf(PETSC_COMM_WORLD,"sovling\n");
	ierr = KSPSetFromOptions(ksp);CHKERRQ(ierr);
	ierr = KSPSolve(ksp,pb,px);CHKERRQ(ierr);


	ierr = VecView(px,PETSC_VIEWER_STDOUT_WORLD);CHKERRQ(ierr);
	return ierr;
} 


int petsc_init(fk::matrix<double> &amatrix, fk::vector<double>&b, fk::vector<double>&u)
{
	Vec px,pb,pu;
	Mat A;
	PetscErrorCode ierr;
	PetscScalar *v;
	PetscInt *j;
	PetscInt m,n;
	double* vtest;
	m = amatrix.nrows();
	n = amatrix.ncols();

	//Create Petsc Sparse Matrix
        ierr = MatCreate(PETSC_COMM_WORLD,&A);CHKERRQ(ierr);
	MatSetType(A, MATMPIAIJ);
	ierr = MatSetSizes(A,PETSC_DECIDE,PETSC_DECIDE,m,n);CHKERRQ(ierr);
	ierr = MatSetFromOptions(A);CHKERRQ(ierr);
	ierr = MatMPIAIJSetPreallocation(A,n,NULL,n,NULL);CHKERRQ(ierr);
	ierr = MatSeqAIJSetPreallocation(A,n,NULL);CHKERRQ(ierr);
	MatSetUp(A);
	
	//ierr = MatCreateDense(PETSC_COMM_WORLD,PETSC_DECIDE,PETSC_DECIDE,m,n, NULL,&A);CHKERRQ(ierr);
	//MatSetUp(A);
	PetscMalloc1(n, &j);
	PetscMalloc1(n, &v);

	for (int i = 0; i < m; i++){ 
		fk::matrix<double> sub(amatrix.extract_submatrix(i,0,1,n));
		vtest = sub.data();
		//vtest = (amatrix.extract_submatrix(i,0,1,n)).data();
		//printf("Test: %lf %lf %lf %lf\n",vtest[0],vtest[1],vtest[2],vtest[3]);
		//printf("Test: %lf %lf %lf %lf\n",sub(0,0),sub(0,1),sub(0,2),sub(0,3));

		for(int vx = 0; vx<n; vx++){
		      j[vx] = vx;
                      //v[vx] = amatrix(i,vx);
    		}
		ierr = MatSetValues(A,1,&i,n,j,vtest,ADD_VALUES);CHKERRQ(ierr);
   	}
	ierr = MatAssemblyBegin(A,MAT_FINAL_ASSEMBLY);CHKERRQ(ierr);
	ierr = MatAssemblyEnd(A,MAT_FINAL_ASSEMBLY);CHKERRQ(ierr);
	MatView(A, PETSC_VIEWER_STDOUT_WORLD);

	//Setup petsc Vectors (u,b)
	ierr = VecCreate(PETSC_COMM_WORLD,&pu);CHKERRQ(ierr);
	ierr = VecSetSizes(pu,PETSC_DECIDE,n);CHKERRQ(ierr);
	ierr = VecSetFromOptions(pu);CHKERRQ(ierr);
	for (int i=0; i<n; i++) {
  		PetscScalar v2 = (PetscScalar)u(i);
		ierr = VecSetValues(pu,1,&i,&v2,ADD_VALUES);CHKERRQ(ierr);
	}

	ierr = VecAssemblyBegin(pu);CHKERRQ(ierr);
	ierr = VecAssemblyEnd(pu);CHKERRQ(ierr);
	ierr = VecView(pu,PETSC_VIEWER_STDOUT_WORLD);CHKERRQ(ierr);
	ierr = VecDuplicate(pu,&pb);CHKERRQ(ierr);
	

	merge_petsc(pb, pu, A);

}

int petsc_init(int m, int n)
{
	Vec px,pb,pu;
	Mat A;
	PetscErrorCode ierr;
	PetscScalar *v;
	PetscInt *j;

	//Create Petsc Sparse Matrix
        ierr = MatCreate(PETSC_COMM_WORLD,&A);CHKERRQ(ierr);
	MatSetType(A,MATMPIAIJ);
	ierr = MatSetSizes(A,PETSC_DECIDE,PETSC_DECIDE,m,n);CHKERRQ(ierr);
	ierr = MatSetFromOptions(A);CHKERRQ(ierr);
	ierr = MatMPIAIJSetPreallocation(A,n,NULL,n,NULL);CHKERRQ(ierr);
	ierr = MatSeqAIJSetPreallocation(A,n,NULL);CHKERRQ(ierr);
	MatSetUp(A);
	ierr = MatAssemblyBegin(A,MAT_FINAL_ASSEMBLY);CHKERRQ(ierr);
	ierr = MatAssemblyEnd(A,MAT_FINAL_ASSEMBLY);CHKERRQ(ierr);
	MatView(A, PETSC_VIEWER_STDOUT_WORLD);

	// Create Petsc Vectors (u,b)
	ierr = VecCreate(PETSC_COMM_WORLD,&pu);CHKERRQ(ierr);
	ierr = VecSetSizes(pu,PETSC_DECIDE,n);CHKERRQ(ierr);
	ierr = VecSetFromOptions(pu);CHKERRQ(ierr);
	ierr = VecAssemblyBegin(pu);CHKERRQ(ierr);
	ierr = VecAssemblyEnd(pu);CHKERRQ(ierr);
	ierr = VecView(pu,PETSC_VIEWER_STDOUT_WORLD);CHKERRQ(ierr);
	ierr = VecDuplicate(pu,&pb);CHKERRQ(ierr);


	merge_petsc(pb, pu, A);
}

int main(int argc,char **argv)
{
	
	myInt m,n;
	int rank,size;
	PetscErrorCode ierr;

	PetscInitialize(&argc,&argv,(char*)0,"TEST");
	MPI_Comm_rank(PETSC_COMM_WORLD,&rank);
	MPI_Comm_size(PETSC_COMM_WORLD,&size);
	srand (time(NULL));

	m = atoi(argv[1]);
	n = atoi(argv[2]);

	printf("%d %d\n",m,n);

	// Generating matrix, may use parallel load, or direct read
	if(rank == 0){
		fk::matrix<double> amatrix (m,n);
		fk::vector<double> u(n);
		
		for(int i=0;i<m;i++){
			for(int j = 0; j< n; j++){
				amatrix(i,j) = (double)(rand()%10) + (double)(rand()%10)/100;
			}
			printf("TestRand: %lf %lf %lf %lf\n",amatrix(i,0),amatrix(i,1),amatrix(i,2),amatrix(i,3));
		}
		for(int i=0; i<m;i++)
			u(i) = (double)(rand()%10) + (double)(rand()%10)/100;
		fk::vector<double> b(amatrix*u);		
		printf("Done\n");
		petsc_init(amatrix, b, u);
	}else{
		petsc_init(m,n);
	}

	PetscPrintf(PETSC_COMM_WORLD,"FINAL\n");	
	ierr = PetscFinalize();
	return ierr;
}

**Comment by haolu12** [comment]
Petsc code fore taking the fk::matrix data and fk::vector from single to do gmres

**Comment by mkstoyanov** [comment]
Stale issue, open a new one, if still relevant.
