### ISSUE TITLE
clang-format in ci

### ISSUE THREAD

**Issue by mkstoyanov** [project-asgard/asgard#652]
Right now, we have the clang-format-check script and the CI is doing more or less a copy of the same command, but that's hard-coded into the AWS CI.

We should change the CI so that the check is done from the script in the repo.

That will give us easier and more fine-grained control.

Meanwhile, we can ignore the clang-format-check.

**Comment by quantumsteve** [comment]
I just made this change to the buildspec on AWS codebuild. It should run on your next push to #651.

Do you have access to our AWS organization?

**Comment by mkstoyanov** [comment]
Great! Seems to be working.
