### ISSUE TITLE
Crash on landau 1x3v

### ISSUE THREAD

**Issue by stefan-schnake** [project-asgard/asgard#660]
**Describe the bug**

**To Reproduce**
1. Current develop
2. Build with `cmake -DASGARD_RECOMMENDED_DEFAULTS=ON -DASGARD_IO_HIGHFIVE=ON -DASGARD_USE_CUDA=ON`
3. Change $\nu$ in `pde_collisional_landau_1x3v.hpp` to `1e-2`
4. Run with ```OMP_NUM_THREADS=8 nohup ./asgard -p landau_1x3v -d 3 -l "5 5 5 5" -m 5 -t 0.009817477042468 -x -n 5094 --wave_freq 4 --tol 1e-14 --max_adapt_levels "5 5 5 5" --adapt --thresh 1e-8 --inner_it 10 --memory 40000 > asgard_out.txt &```

**Expected behavior**
Crash uring 9th timestep.  Error given is 
```
terminate called after throwing an instance of 'std::bad_alloc' 
  what():  std::bad_alloc
```

**System:**
 - run on andremarie

**Additional context**

**Comment by mkstoyanov** [comment]
Trying to reproduce right now, but I have a dumb question. Have you tried to run a basic cuda problem? This error can happen if there is a mismatch between the cuda version installed and the cuda driver. Basically, the machine may just need a reboot.

**Comment by mkstoyanov** [comment]
Or it may be using up too much memory ... ugh!

**Comment by mkstoyanov** [comment]
It's running out of memory!

**Comment by stefan-schnake** [comment]
> Trying to reproduce right now, but I have a dumb question. Have you tried to run a basic cuda problem? This error can happen if there is a mismatch between the cuda version installed and the cuda driver. Basically, the machine may just need a reboot.

Tried after reboot.  Same error.

**Comment by mkstoyanov** [comment]
This is not a bug but the math algorithm using too much memory. It will be delegated to the block-global Kronmult, can close for now.
