### ISSUE TITLE
time_advance-test could use more threads

### ISSUE THREAD

**Issue by quantumsteve** [project-asgard/asgard#666]
**Is your feature request related to a problem? Please describe.**

I'd like to reduce the execution time of `time_advance-test` and `time_advance-test-mpi-*`, especially on the CI systems.

**Describe the solution you'd like**

time_advance-test current sets `OMP_NUM_THREADS=2` Maybe we check for an environment variable?

mpi tests set `OMP_NUM_THREADS=1`. Perhaps set this to OMP_NUM_THREADS / # of processes?

**Describe alternatives you've considered**

**Additional context**

**Comment by mkstoyanov** [comment]
The majority of the tests are too small for multi-threading to really help, I don't know if this will really help. Have you checked this by running the tests manually with different number of threads?

I think the `OMP_NUM_THREADS` directives should be removed from CMake. The `OMP_NUM_THREADS` variable should be controlled from the external environment. Unless we are running tests in parallel (which I think is a bad idea), we don't need to mess with OMP in the CMake code.

We can do the same for the MPI threads, just reduce the number of threads in the CI environment.

Can we just set the `OMP_NUM_THREADS` variable in the CI?

**Comment by quantumsteve** [comment]
At least on my laptop, any value of OMP_NUM_THREADS gives about the same runtime.

OMP_NUM_THREADS = 8
```
$ time ./time_advance-tests 
real	0m43.001s
user	2m51.847s
sys	0m11.690s
```
OMP_NUM_THREADS = 2
```
real	0m40.855s
user	0m49.029s
sys	0m9.842s
```
OMP_NUM_THREADS=1
```
$ time ./time_advance-tests 
real	0m42.152s
user	0m30.718s
sys	0m9.735s
```

**Comment by mkstoyanov** [comment]
Threads benefit large problems only and I've noticed that OpenBLAS drops performance massively for many threads and small problems. I usually stick to OMP threads to be the number of physical cores on the system.

Oversubscribing is another potential issue, with the OMP and MPI combo. Setting MPI to use 1 OMP thread is a reasonable thing to do.
