### ISSUE TITLE
implement new FMWT construction

### ISSUE THREAD

**Issue by grahamlopez** [project-asgard/asgard#67]
ASGarD
    asgardasgard
    Issues
    #67

Open
Opened 1 month ago by Graham Lopez
Close issue
New issue
implement new FMWT construction

Ed has a new optimized version available in the matlab.
Related issues
0

Related merge requests
1

    Optimized Application of FMWT
    asgard/asgard !58
Graham Lopez @bgl added performance label 1 month ago
Graham Lopez
Graham Lopez @bgl · 2 weeks ago
Owner

this could be related to !58
Edited by Graham Lopez 4 days ago
Graham Lopez @bgl assigned to @tqd 2 weeks ago
Graham Lopez @bgl mentioned in issue #52 2 weeks ago
Graham Lopez
Graham Lopez @bgl · 2 weeks ago
Owner

related to #52 ?
Graham Lopez
Graham Lopez @bgl · 4 days ago
Owner

@dg6, @tqd is this really the same thing as !58 and #52 ?
I have in the description "construction" but what @tqd has done is applying the operator. So is there also a new construction routine, or did I just misunderstand way back when I first made this issue?
Edited by Graham Lopez 4 days ago

**Comment by grahamlopez** [comment]
@tyounkin says that this is not the same thing as #52 

This one is to use a completely different basis, but that status of that work is not well-known by us

**Comment by bmcdanie** [comment]
our new FMWT application method is pretty quick with the new views update - do we still need this? @grahamlopez @dlg0 @tyounkin ?

**Comment by dlg0** [comment]
The non-wavelet basis work is not complete in the matlab, and we are not sure what the future is for that effort, so we can likely scrap this issue.
