### ISSUE TITLE
Divergence in Kronmults

### ISSUE THREAD

**Issue by stefan-schnake** [project-asgard/asgard#670]
**Describe the bug**

There is a discrepancy between the global and local kronmults when adaptivity is enabled.  This is causing instabilities in the collision operator solve.

**To Reproduce**
1. Current git hash
2. ```OMP_NUM_THREADS=8 ./asgard -p two_stream -d 3 -l "7 7" -x -t 2.3438e-3 -n 5 -m 7 --wave_freq 1 --adapt --thresh 1e-6 --kron-mode sparse ```

**Expected behavior**
Results should be the same within machine epsilon when `USE_GLOBAL_KRON=ON/OFF`.  Diverges at the 4th timestep.

**System:**
 - andremarie

**Additional context**
Issue only arrises when adaptivity is enabled and could be due to padding.  If `thresh=1e-3`, then the results match for 100 timesteps.  In this case, only four elements are added for padding.

**Comment by mkstoyanov** [comment]
@stefan-schnake I figured it out, don't waste time looking into it right now. I'll make the PR later today, though I will need to double-check the fix.
