### ISSUE TITLE
discourage use of `.data()`

### ISSUE THREAD

**Issue by grahamlopez** [project-asgard/asgard#68]
ASGarD
    asgardasgard
    Issues
    #68

Open
Opened 3 weeks ago by Graham Lopez
Close issue
New issue
discourage use of `.data()`

related to #22 (closed)

at a minimum, let's make the name super-painfully long and gross to use.
Related issues
0

Graham Lopez @bgl added hygeine label 3 weeks ago
Green, David L @dg6 · 1 week ago
Owner

Is this related to how we get access to the "data" underlying the tensor class? If so, I'm curious about how I go about viewing what data those tensors actually contain in a debugger? In Allinea Forge, I unpack the initial_condition variable which is a fk::vector<P> but I cannot figure out how to actually see what is in there?

![image](https://user-images.githubusercontent.com/5647645/59166652-d960cb80-8af9-11e9-8303-a1d5c9d362f5.png)

So how does one actually get to the data?

(If it's not related to this ... please ignore)
Edited by Green, David L 1 week ago
Graham Lopez
Graham Lopez @bgl · 1 week ago
Owner

Yes and no.

This is related to how we use the API for the matrix/vector classes within the C++ code.

As for the debugging, how the API is presented will have no effect on how a debugger sees the underlying memory. I'm not sure what Allinea is showing you with the element you have highlighted, but the memory address holding the data should just be the one on the line above.

Note that if you just want to see the values in a matrix/vector, check out their ".print()" methods: these were designed specifically for viewing/debugging purposes, and we have found them quite useful.

**Comment by mkstoyanov** [comment]
Stale issue, open a new one, if still relevant.
