### ISSUE TITLE
Kronmult discrepancy

### ISSUE THREAD

**Issue by mkstoyanov** [project-asgard/asgard#689]
I'm getting a discrepancy in the global and local kronmult for the vlasov PDE.

I'm using the following command:
```
./asgard -p vlasov -l "3 3" -m 4 -d 2 -x -t 0.0001 -n 2
```

@stefan-schnake can you please verify that this is the correct command and I'm not doing something wrong. Can you also make a quick comment on any specific features of the terms being used here, e.g., multiple partial terms, no explicit terms, multiple non-identity terms, etc. Talk to me directly if you don't want to do a complete write up.

**Comment by stefan-schnake** [comment]
Usually this is run with `-d 3`, but that shouldn't have a result on the output.  Are both results reasonable or is one crazy while the other is fine?

**Comment by mkstoyanov** [comment]
Never mind, it was the preconditioner.
