### ISSUE TITLE
time-advance-tests with scalapack solver are failing

### ISSUE THREAD

**Issue by quantumsteve** [project-asgard/asgard#691]
**Describe the bug**

`ctest -R time_advance-test-mpi_4 --output-on-failure`

```
time_advance-tests: /home/svh/Documents/asgard/src/asgard_vector.hpp:1084: asgard::fk::vector<P, mem, resrc>::vector(const asgard::fk::vector<P, omem, resrc>&, int, int, bool) [with asgard::mem_type m_ = asgard::mem_type::view; <template-parameter-2-2> = void; asgard::mem_type omem = asgard::mem_type::owner; P = float; asgard::mem_type mem = asgard::mem_type::view; asgard::resource resrc = asgard::resource::host]: Assertion `stop_index < vec.size()' failed.
time_advance-tests: /home/svh/Documents/asgard/src/asgard_vector.hpp:1084: asgard::fk::vector<P, mem, resrc>::vector(const asgard::fk::vector<P, omem, resrc>&, int, int, bool) [with asgard::mem_type m_ = asgard::mem_type::const_view; <template-parameter-2-2> = void; asgard::mem_type omem = asgard::mem_type::owner; P = float; asgard::mem_type mem = asgard::mem_type::const_view; asgard::resource resrc = asgard::resource::host]: Assertion `stop_index < vec.size()' failed.
time_advance-tests: /home/svh/Documents/asgard/src/asgard_vector.hpp:1084: asgard::fk::vector<P, mem, resrc>::vector(const asgard::fk::vector<P, omem, resrc>&, int, int, bool) [with asgard::mem_type m_ = asgard::mem_type::const_view; <template-parameter-2-2> = void; asgard::mem_type omem = asgard::mem_type::owner; P = float; asgard::mem_type mem = asgard::mem_type::const_view; asgard::resource resrc = asgard::resource::host]: Assertion `stop_index < vec.size()' failed.
time_advance-tests: /home/svh/Documents/asgard/src/asgard_vector.hpp:1084: asgard::fk::vector<P, mem, resrc>::vector(const asgard::fk::vector<P, omem, resrc>&, int, int, bool) [with asgard::mem_type m_ = asgard::mem_type::view; <template-parameter-2-2> = void; asgard::mem_type omem = asgard::mem_type::owner; P = float; asgard::mem_type mem = asgard::mem_type::view; asgard::resource resrc = asgard::resource::host]: Assertion `stop_index < vec.size()' failed.
```

**To Reproduce**
1. git commit hash being built

def3174fd42a1a0010b9286a4f3c1afd308db72b

2. cmake command

cmake ../ -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++ -DASGARD_USE_MPI=1 -DASGARD_USE_SCALAPACK=1 -DASGARD_RECOMMENDED_DEFAULTS=1

3. full program/test invocation command

ctest -R time_advance-test-mpi_4 --output-on-failure

4. additional steps 

**Expected behavior**

**System:**
 - system name [e.g. fusiont5, summit] 
 
AWS CodeBuild - asgard-unit-mpi-gxx-scalapack

 - modules loaded [e.g. output of `module list`]

none

 - other systems where this is reproducible [e.g. "my laptop", "none"] 
 
 my laptop

**Additional context**

Found in #685. Tests disabled [here](https://github.com/project-asgard/asgard/pull/685/commits/316d0f811e8835963f0e5091446fe4aab268630f)

**Comment by mkstoyanov** [comment]
This may or may not be an easy fix but it raises a question to discuss in the next meeting. Should we continue supporting `SCALAPACK`? Given how much more expensive it is to form the Kronecker matrices, even compared to the local kronmult, perhaps we should focus efforts on GMRES+MPI for local kronmult instead.

Let's discuss on the next meeting.

**Comment by mkstoyanov** [comment]
Scalapack support was discontinued in #743
