### ISSUE TITLE
how to cite the code

### ISSUE THREAD

**Issue by grahamlopez** [project-asgard/asgard#7]
ASGarD
    asgardasgard
    Issues
    #7

Open
Opened 6 months ago by Graham Lopez0 of 1 task completed
Close issue
New issue
how to cite the code

Until we get a citation paper in place, look into a DOI or other code-friendly citation method.

    is it transferable if/when we want to move the repo to be publicly available?

Related issues
0

    Graham Lopez
Graham Lopez @bgl · 5 months ago

see # 17 "Software Citation Today and Tomorrow" at https://ideas-productivity.org/events/hpc-

In the Q&A, the best thing for today is still a software citation paper. During the presetnation, they suggest specifically JOSS, which is peer-reviewed but non-adversarial.

Repo-based DOIs are suggested for reproducibility purposes, not so much attributive purposes.
Graham Lopez @bgl assigned to @dg6 1 month ago
Graham Lopez
Graham Lopez @bgl · 1 month ago
Owner

We could also go for Computer Physics Communications (https://www.journals.elsevier.com/computer-physics-communications)
Graham Lopez
Graham Lopez @bgl · 1 month ago
Owner

Here is how we would submit to JOSS
Green, David L
Green, David L @dg6 · 1 month ago
Owner

We have the https://github.com/orgs/project-asgard organization, so I expect the next step here is to move there, then start going through the submission process (this would be after we have a functional time loop though).

**Comment by mkstoyanov** [comment]
Stale issue, open a new one, if still relevant.
