### ISSUE TITLE
use 64-bit integers for all indexing functions in tensors

### ISSUE THREAD

**Issue by grahamlopez** [project-asgard/asgard#74]
This is partially done/WIP at #110 
ASGarD
    asgardasgard
    Issues
    #74

Open
Opened 2 weeks ago by McDaniel, Benjamin T
Close issue
New issue
use 64-bit integers for all indexing functions in tensors

the vectors for batch gemm output/workspace are very large and much be indexed with >32bit numbers.

use 64-bit numbers for the index calculations in build_batches and modify the tensor functions to support those types.
Related issues
0

Related merge requests
1

    Feature/setup and timeloop
    asgard/asgard !69

McDaniel, Benjamin T @3bm added bug label 2 weeks ago
McDaniel, Benjamin T @3bm mentioned in merge request !69 (merged) 2 weeks ago
McDaniel, Benjamin T
McDaniel, Benjamin T @3bm · 2 weeks ago
Developer

I'm going to suggest we use 64 bit integers for the size, rows, and columns of tensors. this, to me, is less error prone than deciding everywhere based on the problem instance whether we need 32 or 64 bits, and the space difference is probably negligible compared to what we need to solve the pde.

additionally, this doesn't prevent us from still using int32 as a type for the tensor elements, so it won't affect much the size of the element table.
McDaniel, Benjamin T
McDaniel, Benjamin T @3bm · 2 weeks ago
Developer

on hold pending solution of #75 (closed)
McDaniel, Benjamin T @3bm added someday label 2 weeks ago

**Comment by bmcdanie** [comment]
suggesting we close this as we've decided not to move in this direction @grahamlopez

**Comment by grahamlopez** [comment]
On Thu, Dec 12, 2019 at 11:20:57AM -0800, Tyler McDaniel wrote:
>suggesting we close this as we've decided not to move in this direction @grahamlopez

Makes sense to me.
