### ISSUE TITLE
get rid of casts for signed/unsigned comparisons

### ISSUE THREAD

**Issue by grahamlopez** [project-asgard/asgard#8]
ASGarD
    asgardasgard
    Issues
    #8

Open
Opened 6 months ago by Graham Lopez
Close issue
New issue
get rid of casts for signed/unsigned comparisons

casting to get rid of signed/unsigned comparison compiler warnings is bad, in general. We always prefer signed integers in the code. We need to find the good way to deal with this.
Related issues
0

    Graham Lopez @bgl added hygeine label 6 months ago
    Graham Lopez @bgl added someday label 5 months ago
    Graham Lopez
Graham Lopez @bgl · 4 months ago

@3bm take a look at this and let me know your thoughts http://ithare.com/c-thoughts-on-dealing-with-signedunsigned-mismatch/

**Comment by bmcdanie** [comment]
currently we are:

casting unsigned quantities (like `.size()` returns from STL) to signed quantities. where it is possible that `size()` is `>=INT_MAX`, we precede this case with an assertion.

switching to `ssize()` in C++20: https://en.cppreference.com/w/cpp/iterator/size should help.
