### ISSUE TITLE
make quad_num global and set to deg+1

### ISSUE THREAD

**Issue by grahamlopez** [project-asgard/asgard#82]
ASGarD
    asgardasgard
    Issues
    #82

Open
Opened 1 week ago by Green, David L
Close issue
New issue
make quad_num global and set to deg+1

The quad_num variable is used in a few places. It sets the number of quadrature points over which to perform an integration. The Legendre functions over which the integrations are being performed have a maximum degree (set by the global deg). So, to avoid extra work at low deg and errors at high deg, we should set quad_num = deg+1 consistently throughout the code.

I'd have a go at this, but I am 100% certain that my approach to a global variable will be embarrassing.

@bgl had suggested some set of global variables to handle other things. Perhaps we can get one variable done so I can see where to add this?
Related issues
0

Green, David L @dg6 added bug feature hygeine labels 1 week ago

Graham Lopez @bgl · 1 week ago
Owner

At one point, I had suggested some kind of globally-accessible const singleton object, but either it never gained priority attention from us, or we tried and couldn't get it to work.

I don't want to compromise with a set of global variables; that's bad karma - the C++ gods will frown on us and our crops will struggle.

Graham Lopez
Graham Lopez @bgl · 1 week ago
Owner

I gave this a go and modified the first argument to legendre_weights() to be degree + 1 in both coefficients.cpp and transformations.hpp, but NOT basis.cpp since these are set much higher (2^6).

Not only will it require a change to some of the matlab test input generation (coefficients_tests.cpp), but also some tolerances we are using (time_advance_tests.cpp and batch_tests.cpp) that we might want to think a little bit about.

**Comment by grahamlopez** [comment]
I'm going to hold this one until @dlg0 is done with the matlab test generation retool

**Comment by efdazedo** [comment]
In transformations.hpp (branch develop) around line 64,  quadrature_num is set at 10. 
Perhaps it should be dependent on the value of "degree", say   
quadrature_num = degree + 1; // better efficiency with low polynomial degree
or   
quadrature_num = MAX( degree + 1, 10 ); // use at least 10 or higher, for high polynomial degree

**Comment by bmcdanie** [comment]
I'm going to suggest we ingest degree as an argument rather than quadrature number in the weights generation routine, and then use `MAX( degree + 1, 10 ); ` as Ed suggests for the quadrature number within the routine.

**Comment by bmcdanie** [comment]
ah, now I see that while `coefficients.cpp` and `transformations.hpp` use 10 as quadrature number, the basis routine uses 2^6. May need to rethink.

**Comment by dlg0** [comment]
@MollyRaver do you know why that 10^6 number is so large?

**Comment by bmcdanie** [comment]
just a note - if we use 10 as the quadrature number there, the coefficients are different (of course) and the coefficient tests fail, but the time advance test results still fall within our tolerances.

the difference in reported error for time advance (just from spot checking a few sizes) is negligible, as well.

**Comment by bmcdanie** [comment]
if we need to allow for different quad nums, I have a plan that will work - just let me know if we need to do that or if the math works for the smaller quad num in the basis component.

**Comment by efdazedo** [comment]
Do you mean the code uses  10 quadrature points for each dimension so tensor product of 10x10x10x10x10x10    requires 10^6 quadrature points (for each element)? So in general   it is Q^6,  if there are Q quadrature points in each dimension?  I wonder whether the sparse grid idea can be used again to reduce the number of quadrature points in 6 dimensions.

**Comment by efdazedo** [comment]
In MPI, there is MPI_Info_set and MPI_Info_get (https://www.mpi-forum.org/docs/mpi-2.1/mpi21-report-bw/node194.htm) to handle key value (string) pairs. Perhaps something similar (instead of global variables) can be used to implement some global key value pairs, such as global deg or global number of quadrature points. Just a thought.

**Comment by efdazedo** [comment]
Just a reminder that in a variable separable formulation, say in 3D,   F(x,y,z) = sum( c(i,j,k) * f(i,x) * g(j,y) * h(k,z) ), evaluation of this function onto a tensor product rectangular grid (say at quadrature points) can also be formulated as kronecker products    kron( Tz, Ty, Tx) * c where Tz, Ty, Tx are matrices that contain values of the basis functions on their 1-d grid points. So if you do need to evaluate the 10^6 function values on the 10x10x10x10x10x10 rectangular grid of quadrature locations, you can do so efficiently as 6-dimensional kronecker product, instead of very deeply nested loops. Just a suggestion.

**Comment by dlg0** [comment]
From @MollyRaver (Lin) ...

https://asgard-crew.slack.com/files/ULVDSSFHR/FRVJ2CJQP/image.png 

this is the difference by changing [p_legendre_roots,p_legendre_weights]=lgwt(N,-1,1); to

[p_legendre_roots,p_legendre_weights]=lgwt(k+1,-1,1);
It works by only using k+1 quadrature points.

So yes, we can update this. It will mean updating the matlab also and the associated tests for the wavelet generation routines.

**Comment by bmcdanie** [comment]
Great - I can handle that
