### ISSUE TITLE
vector*matrix<view> makes a copy for fk::matrix<int, view>

### ISSUE THREAD

**Issue by grahamlopez** [project-asgard/asgard#84]
ASGarD
    asgardasgard
    Issues
    #84

Open
Opened 1 week ago by Graham Lopez
Close issue
New issue
vector*matrix<view> makes a copy for fk::matrix<int, view>

the way we do integer multiplication with _igemm() requires a pre-transpose, which in turn requires a copy. So there is an extra (owner) copy made in the case where a view is passed in. This should be fixed.
Related issues
0

Graham Lopez @bgl added bug help_wanted labels 1 week ago

**Comment by bmcdanie** [comment]
this was fixed: https://github.com/project-asgard/asgard/blob/ea743966195cf9c577a29f1100ceba87609da77f/src/lib_dispatch.cpp#L321
