### ISSUE TITLE
Perform partial explicit kron to increase matrix size in batch gemm

### ISSUE THREAD

**Issue by grahamlopez** [project-asgard/asgard#86]
ASGarD
    asgardasgard
    Issues
    #86

Open
Opened 1 week ago by McDaniel, Benjamin T
Close issue
New issue
Perform partial explicit kron to increase matrix size in batch gemm

@dg6, today I discussed w/ @e6d an idea for improving our performance, especially when degree is small: explicitly performing the kron product for pairs of the small "tmp" operator matrices in the batch gemm, i.e., for

(A1 tensor A2 tensor A3 tensor A4 tensor A5 tensor A6) * x

we could instead perform

    A1 tensor A2 = A1', A3 tensor A4 = A2', A5 tensor A6 = A3'

followed by

    (A1' tensor A2' tensor A3') * x via batched gemm as before.

According to our calculations, step 2 above takes 4 times more flops to calculate vs. the original code: for the 6d case, 4 * deg^8 flops vs. deg^8 flops.

We also have to account for the small number of flops and small storage space requirements of A1', A2', A3', but this is negligible.

We should expect that if we have 4+x peak flop rate vs. bandwidth on a device (after accounting for number of bytes per element), this intermediate explicit kron product will be faster than our original version.

Edited 1 week ago by McDaniel, Benjamin T
Related issues
0

McDaniel, Benjamin T @3bm added performance someday labels 1 week ago
McDaniel, Benjamin T @3bm changed the description 3 times within 5 minutes 1 week ago

Green, David L
Green, David L @dg6 · 1 week ago
Owner

Yes, this is a great idea. This will likely be something to try after we get a GPU implementation up and running. Or, possibly something for Harry to start with in July / August.

**Comment by mkstoyanov** [comment]
Stale issue, open a new one, if still relevant.
